import json

rest = [
# ── ADJECTIVES ──
{"w":"adequate","pos":"adj","cat":"ADJ","m":"enough; satisfactory","tr":"memadai / cukup","i":"sufficient for a specific need or requirement","e":"Make sure the budget is adequate to cover all project costs.","s":["sufficient","enough","satisfactory"],"wf":[{"w":"adequacy","p":"noun"},{"w":"adequately","p":"adv"}],"ety":"Dari bahasa Latin 'adaequatus' (dibuat setara), dari 'ad-' (ke) + 'aequare' (membuat setara). Masuk ke bahasa Inggris pada abad ke-17.","q":"The training provided was not ___ to prepare staff for the new system."},
{"w":"comprehensive","pos":"adj","cat":"ADJ","m":"covering everything","tr":"komprehensif / menyeluruh","i":"including all or nearly all elements or aspects","e":"The report provides a comprehensive overview of market trends.","s":["thorough","complete","extensive"],"wf":[{"w":"comprehend","p":"verb"},{"w":"comprehension","p":"noun"},{"w":"comprehensively","p":"adv"}],"ety":"Dari bahasa Latin 'comprehensivus', dari 'comprehendere' (memahami), dari 'com-' (bersama) + 'prehendere' (merebut). Masuk ke bahasa Inggris pada abad ke-17.","q":"The consultant prepared a ___ report covering all aspects of the business."},
{"w":"confidential","pos":"adj","cat":"ADJ","m":"private; secret","tr":"rahasia / bersifat rahasia","i":"intended to be kept secret","e":"All client information must be treated as confidential.","s":["private","classified","restricted"],"wf":[{"w":"confidence","p":"noun"},{"w":"confidentially","p":"adv"},{"w":"confidentiality","p":"noun"}],"ety":"Dari bahasa Latin 'confidentia' (kepercayaan), dari 'confidere' (mempercayai sepenuhnya). Makna kerahasiaan berkembang pada abad ke-18.","q":"All salary information is strictly ___ and must not be shared with other employees."},
{"w":"consecutive","pos":"adj","cat":"ADJ","m":"following in order","tr":"berturut-turut","i":"following each other continuously without interruption","e":"The company has reported profits for five consecutive quarters.","s":["successive","continuous","sequential"],"wf":[{"w":"consecutively","p":"adv"},{"w":"consecutiveness","p":"noun"}],"ety":"Dari bahasa Latin 'consecutivus', dari 'consequi' (mengikuti), dari 'con-' (bersama) + 'sequi' (mengikuti). Masuk ke bahasa Inggris pada abad ke-17.","q":"The team won the championship for three ___ years."},
{"w":"dedicated","pos":"adj","cat":"ADJ","m":"committed to a purpose","tr":"berdedikasi / berkomitmen","i":"devoted to a task or purpose","e":"She is a dedicated employee who always goes above and beyond.","s":["committed","devoted","hardworking"],"wf":[{"w":"dedicate","p":"verb"},{"w":"dedication","p":"noun"}],"ety":"Dari bahasa Latin 'dedicare' (mengabdikan), dari 'de-' (sepenuhnya) + 'dicare' (menyatakan). Masuk ke bahasa Inggris pada abad ke-15.","q":"We are looking for a ___ professional who is passionate about customer service."},
{"w":"eligible","pos":"adj","cat":"ADJ","m":"qualified to receive","tr":"memenuhi syarat / berhak","i":"satisfying the conditions required to receive something","e":"Employees who have worked for two years are eligible for the bonus.","s":["qualified","entitled","suitable"],"wf":[{"w":"eligibility","p":"noun"},{"w":"ineligible","p":"adj (lawan kata)"}],"ety":"Dari bahasa Latin 'eligibilis' (yang dapat dipilih), dari 'eligere' (memilih), dari 'e-' (keluar) + 'legere' (memilih). Masuk ke bahasa Inggris pada abad ke-15.","q":"Only employees who have completed two years of service are ___ for the pension plan."},
{"w":"flexible","pos":"adj","cat":"ADJ","m":"able to adapt easily","tr":"fleksibel / mudah menyesuaikan diri","i":"willing to change or compromise","e":"We offer flexible working hours to all full-time employees.","s":["adaptable","versatile","adjustable"],"wf":[{"w":"flexibility","p":"noun"},{"w":"flexibly","p":"adv"},{"w":"inflexible","p":"adj (lawan kata)"}],"ety":"Dari bahasa Latin 'flexibilis' (yang dapat ditekuk), dari 'flectere' (menekuk). Masuk ke bahasa Inggris pada abad ke-16.","q":"The company offers ___ working arrangements to help employees balance work and life."},
{"w":"mandatory","pos":"adj","cat":"ADJ","m":"required by law or rules","tr":"wajib / diwajibkan","i":"required by law or rules; compulsory","e":"Attendance at the safety briefing is mandatory for all new staff.","s":["compulsory","required","obligatory"],"wf":[{"w":"mandate","p":"noun/verb"},{"w":"mandatorily","p":"adv"}],"ety":"Dari bahasa Latin Akhir 'mandatorius', dari 'mandatum' (perintah), dari 'mandare' (memerintahkan). Masuk ke bahasa Inggris pada abad ke-18.","q":"It is ___ for all employees to complete the fire safety training within 30 days."},
{"w":"outstanding","pos":"adj","cat":"ADJ","m":"excellent; unpaid","tr":"luar biasa / belum dibayar","i":"exceptionally good; or not yet paid or resolved","e":"She received an award for her outstanding contribution to the team.","s":["excellent","exceptional","remarkable"],"wf":[{"w":"outstandingly","p":"adv"}],"ety":"Gabungan kata 'out-' + 'standing'. Awalnya berarti 'menonjol ke luar'; makna 'belum dibayar' berkembang pada abad ke-17, dan 'luar biasa' pada abad ke-19.","q":"The employee received a bonus for her ___ performance during the product launch."},
{"w":"preliminary","pos":"adj","cat":"ADJ","m":"done before the main event","tr":"pendahuluan / awal","i":"coming before a more important action or event","e":"The preliminary results suggest the campaign was a success.","s":["initial","preparatory","introductory"],"wf":[{"w":"preliminary","p":"noun"},{"w":"preliminarily","p":"adv"}],"ety":"Dari bahasa Latin Modern 'praeliminaris', dari 'prae-' (sebelum) + 'limen' (ambang pintu). Masuk ke bahasa Inggris pada abad ke-17.","q":"The ___ findings of the market research will be presented at next week's meeting."},
{"w":"profitable","pos":"adj","cat":"ADJ","m":"generating financial gain","tr":"menguntungkan","i":"yielding profit or financial gain","e":"The new product line has been highly profitable.","s":["lucrative","rewarding","successful"],"wf":[{"w":"profit","p":"noun/verb"},{"w":"profitably","p":"adv"},{"w":"profitability","p":"noun"}],"ety":"Dari bahasa Prancis Kuno 'profitable', dari 'profiter' (mendapat manfaat), dari bahasa Latin 'profectus' (kemajuan). Masuk ke bahasa Inggris pada abad ke-14.","q":"The overseas expansion proved to be highly ___ in the first year of operation."},
{"w":"qualified","pos":"adj","cat":"ADJ","m":"having the right skills","tr":"berkualifikasi / memenuhi syarat","i":"officially recognized as having the necessary skills","e":"We are looking for a qualified accountant to join our team.","s":["certified","trained","competent"],"wf":[{"w":"qualify","p":"verb"},{"w":"qualification","p":"noun"},{"w":"qualifier","p":"noun"}],"ety":"Dari bahasa Latin Abad Pertengahan 'qualificare' (memberikan kualitas), dari 'qualis' (jenis apa) + 'facere' (membuat). Masuk ke bahasa Inggris pada abad ke-16.","q":"We are seeking a ___ engineer with at least five years of industry experience."},
{"w":"reliable","pos":"adj","cat":"ADJ","m":"consistently dependable","tr":"dapat diandalkan","i":"consistently good in quality or performance","e":"We need a reliable supplier who can meet our deadlines.","s":["dependable","trustworthy","consistent"],"wf":[{"w":"rely","p":"verb"},{"w":"reliability","p":"noun"},{"w":"reliably","p":"adv"}],"ety":"Dari bahasa Prancis 'relier' (mengikat bersama), dari bahasa Latin 'religare' (mengikat kembali). Makna dapat dipercaya berkembang pada abad ke-19.","q":"We need a ___ logistics partner who can guarantee on-time delivery."},
{"w":"substantial","pos":"adj","cat":"ADJ","m":"large in size or amount","tr":"substansial / cukup besar","i":"of considerable importance, size, or worth","e":"The company made a substantial investment in new technology.","s":["significant","considerable","large"],"wf":[{"w":"substance","p":"noun"},{"w":"substantially","p":"adv"}],"ety":"Dari bahasa Latin 'substantialis' (memiliki substansi), dari 'substantia' (substansi). Masuk ke bahasa Inggris pada abad ke-14.","q":"The company made a ___ profit in the third quarter, exceeding all expectations."},
{"w":"supplemental","pos":"adj","cat":"ADJ","m":"added to complete","tr":"tambahan / pelengkap","i":"provided in addition to what already exists","e":"The supplemental report contains additional financial data.","s":["additional","extra","complementary"],"wf":[{"w":"supplement","p":"noun/verb"},{"w":"supplementary","p":"adj"}],"ety":"Dari bahasa Latin 'supplementum' (pengisian), dari 'supplere' (mengisi), dari 'sub-' (di bawah) + 'plere' (mengisi). Masuk ke bahasa Inggris pada abad ke-17.","q":"The company provided ___ health insurance to cover expenses not included in the basic plan."},
{"w":"temporary","pos":"adj","cat":"ADJ","m":"lasting for a short time","tr":"sementara","i":"lasting for only a limited period of time","e":"The road closure is temporary and will last about two weeks.","s":["short-term","interim","provisional"],"wf":[{"w":"temporarily","p":"adv"},{"w":"temporariness","p":"noun"}],"ety":"Dari bahasa Latin 'temporarius' (dari musim), dari 'tempus' (waktu). Masuk ke bahasa Inggris pada abad ke-16.","q":"The company hired ___ staff to handle the increased workload during the holiday season."},
{"w":"unanimous","pos":"adj","cat":"ADJ","m":"agreed by everyone","tr":"bulat / mufakat","i":"fully agreed by all people involved","e":"The board reached a unanimous decision to approve the merger.","s":["agreed","united","undivided"],"wf":[{"w":"unanimously","p":"adv"},{"w":"unanimity","p":"noun"}],"ety":"Dari bahasa Latin 'unanimus' (satu pikiran), dari 'unus' (satu) + 'animus' (pikiran). Masuk ke bahasa Inggris pada abad ke-17.","q":"The committee reached a ___ decision to approve the new company policy."},
{"w":"urgent","pos":"adj","cat":"ADJ","m":"requiring immediate action","tr":"mendesak","i":"requiring immediate action or attention","e":"Please respond to this urgent request as soon as possible.","s":["pressing","critical","immediate"],"wf":[{"w":"urge","p":"verb"},{"w":"urgency","p":"noun"},{"w":"urgently","p":"adv"}],"ety":"Dari bahasa Latin 'urgens' (menekan), dari 'urgere' (menekan, mendorong). Masuk ke bahasa Inggris pada abad ke-16.","q":"There is an ___ need to address the system failure before the market opens."},
{"w":"valid","pos":"adj","cat":"ADJ","m":"legally or officially acceptable","tr":"sah / berlaku","i":"legally or officially acceptable","e":"Your parking permit is valid for 30 days from the date of issue.","s":["legitimate","acceptable","current"],"wf":[{"w":"validate","p":"verb"},{"w":"validity","p":"noun"},{"w":"validation","p":"noun"}],"ety":"Dari bahasa Latin 'validus' (kuat, efektif), dari 'valere' (menjadi kuat). Masuk ke bahasa Inggris pada abad ke-16.","q":"Your membership card is ___ for one year from the date of registration."},
# ── ADVERBS ──
{"w":"accordingly","pos":"adv","cat":"ADV","m":"in a way that is appropriate","tr":"dengan demikian / sesuai","i":"in a way that is appropriate to the circumstances","e":"Please review the updated guidelines and act accordingly.","s":["appropriately","correspondingly","therefore"],"wf":[{"w":"accord","p":"noun/verb"},{"w":"according","p":"prep"}],"ety":"Dari kata 'accord' (kesepakatan), dari bahasa Prancis Kuno 'acorder', dari bahasa Latin 'accordare' (sehati). Bentuk kata keterangan masuk ke bahasa Inggris pada abad ke-15.","q":"The new regulations have been issued; please update your procedures ___."},
{"w":"approximately","pos":"adv","cat":"ADV","m":"roughly; about","tr":"kira-kira / sekitar","i":"used to show that something is not exact","e":"The project will take approximately three months to complete.","s":["roughly","about","around"],"wf":[{"w":"approximate","p":"adj/verb"},{"w":"approximation","p":"noun"}],"ety":"Dari bahasa Latin 'approximare' (mendekati), dari 'ad-' (ke) + 'proximus' (terdekat). Masuk ke bahasa Inggris pada abad ke-17.","q":"The renovation will cost ___ $50,000 and take about three months to complete."},
{"w":"consistently","pos":"adv","cat":"ADV","m":"in the same way always","tr":"secara konsisten","i":"in every case or on every occasion; always","e":"She has consistently exceeded her sales targets.","s":["always","regularly","constantly"],"wf":[{"w":"consistent","p":"adj"},{"w":"consistency","p":"noun"}],"ety":"Dari bahasa Latin 'consistere' (berdiri teguh), dari 'con-' (bersama) + 'sistere' (berdiri). Masuk ke bahasa Inggris pada abad ke-17.","q":"The team has ___ delivered high-quality results throughout the year."},
{"w":"efficiently","pos":"adv","cat":"ADV","m":"in a productive way","tr":"secara efisien","i":"in a way that achieves maximum productivity with minimum waste","e":"The new system processes orders more efficiently.","s":["productively","effectively","smoothly"],"wf":[{"w":"efficient","p":"adj"},{"w":"efficiency","p":"noun"}],"ety":"Dari bahasa Latin 'efficientem' (efektif), dari 'efficere' (menyelesaikan), dari 'ex-' (keluar) + 'facere' (melakukan). Masuk ke bahasa Inggris pada abad ke-17.","q":"The automated system handles customer requests more ___ than the old manual process."},
{"w":"immediately","pos":"adv","cat":"ADV","m":"right away","tr":"segera / langsung","i":"at once; without delay","e":"Please contact the IT department immediately if you notice any issues.","s":["instantly","at once","right away"],"wf":[{"w":"immediate","p":"adj"},{"w":"immediacy","p":"noun"}],"ety":"Dari bahasa Latin Abad Pertengahan 'immediatus' (tanpa perantara), dari 'in-' (tidak) + 'mediatus' (di tengah). Masuk ke bahasa Inggris pada abad ke-16.","q":"Please report any workplace accidents ___ to the safety officer."},
{"w":"initially","pos":"adv","cat":"ADV","m":"at the beginning","tr":"pada awalnya","i":"at the beginning; at first","e":"The project was initially expected to take six months.","s":["at first","originally","at the start"],"wf":[{"w":"initial","p":"adj/noun"},{"w":"initiate","p":"verb"}],"ety":"Dari bahasa Latin 'initialis' (dari awal), dari 'initium' (awal), dari 'inire' (masuk). Masuk ke bahasa Inggris pada abad ke-17.","q":"The project was ___ budgeted at $100,000 but costs rose to $150,000."},
{"w":"promptly","pos":"adv","cat":"ADV","m":"quickly and on time","tr":"dengan segera / tepat waktu","i":"with little or no delay; punctually","e":"Please respond to customer inquiries promptly.","s":["quickly","immediately","without delay"],"wf":[{"w":"prompt","p":"adj/verb"},{"w":"promptness","p":"noun"}],"ety":"Dari bahasa Latin 'promptus' (siap, tersedia), dari 'promere' (membawa keluar). Masuk ke bahasa Inggris pada abad ke-15.","q":"All customer complaints must be addressed ___ within 24 hours of receipt."},
{"w":"significantly","pos":"adv","cat":"ADV","m":"by a large amount","tr":"secara signifikan","i":"in a sufficiently great or important way","e":"Sales have increased significantly since the new campaign launched.","s":["considerably","substantially","greatly"],"wf":[{"w":"significant","p":"adj"},{"w":"significance","p":"noun"}],"ety":"Dari bahasa Latin 'significare' (menunjukkan), dari 'signum' (tanda) + 'facere' (membuat). Masuk ke bahasa Inggris pada abad ke-16.","q":"The new marketing strategy ___ increased brand awareness among younger consumers."},
{"w":"temporarily","pos":"adv","cat":"ADV","m":"for a limited time","tr":"untuk sementara","i":"for a limited period of time; not permanently","e":"The office will be temporarily closed for renovations.","s":["briefly","for now","short-term"],"wf":[{"w":"temporary","p":"adj"},{"w":"temporariness","p":"noun"}],"ety":"Dari bahasa Latin 'temporarius' (dari musim). Bentuk kata keterangan masuk ke bahasa Inggris pada abad ke-17.","q":"The main entrance will be ___ closed while the lobby is being renovated."},
{"w":"thoroughly","pos":"adv","cat":"ADV","m":"completely and carefully","tr":"secara menyeluruh","i":"in a thorough manner; completely","e":"Please review the document thoroughly before signing.","s":["completely","carefully","fully"],"wf":[{"w":"thorough","p":"adj"},{"w":"thoroughness","p":"noun"}],"ety":"Dari bahasa Inggris Kuno 'thuruh' (melalui). Awalnya berarti 'dari ujung ke ujung'; makna melakukan sesuatu secara lengkap berkembang pada abad ke-14.","q":"The auditors ___ examined all financial records before issuing their report."},
{"w":"mutually","pos":"adv","cat":"ADV","m":"shared by both sides","tr":"secara bersama / saling","i":"experienced or done by each of two or more parties","e":"Both companies agreed on mutually beneficial terms.","s":["jointly","reciprocally","together"],"wf":[{"w":"mutual","p":"adj"},{"w":"mutuality","p":"noun"}],"ety":"Dari bahasa Latin 'mutuus' (timbal balik, dipinjam), dari 'mutare' (mengubah). Masuk ke bahasa Inggris pada abad ke-16.","q":"The two companies signed a ___ beneficial agreement to share distribution networks."},
# ── PHRASES ──
{"w":"as of","pos":"phrase","cat":"PHRASE","m":"starting from a date","tr":"terhitung mulai / per tanggal","i":"used to indicate the time or date from which something applies","e":"As of January 1, all employees must use the new system.","s":["starting from","effective","beginning"],"wf":[],"ety":"Frasa bahasa Inggris Amerika yang menjadi standar dalam penulisan bisnis pada abad ke-20. Menunjukkan tanggal berlakunya suatu perubahan atau kebijakan.","q":"___ next Monday, all staff will be required to use the new time-tracking system."},
{"w":"at your earliest convenience","pos":"phrase","cat":"PHRASE","m":"as soon as possible","tr":"sesegera mungkin","i":"used to politely ask someone to do something soon","e":"Please contact us at your earliest convenience.","s":["as soon as possible","when you can","promptly"],"wf":[],"ety":"Frasa formal yang memperhalus permintaan mendesak. Umum dalam korespondensi profesional sejak abad ke-19.","q":"Please review the attached contract and return it signed ___."},
{"w":"be subject to","pos":"phrase","cat":"PHRASE","m":"dependent on conditions","tr":"tunduk pada / bergantung pada","i":"likely to be affected by or dependent on something","e":"All prices are subject to change without notice.","s":["dependent on","conditional on","liable to"],"wf":[],"ety":"Dari bahasa Latin 'subjectus' (ditempatkan di bawah), dari 'sub-' (di bawah) + 'jacere' (melempar). Frasa ini menjadi standar dalam bahasa Inggris hukum dan bisnis pada abad ke-18.","q":"All bookings are ___ availability and may be cancelled without prior notice."},
{"w":"due to","pos":"phrase","cat":"PHRASE","m":"because of","tr":"karena / disebabkan oleh","i":"as a result of; caused by","e":"The meeting was cancelled due to a scheduling conflict.","s":["because of","owing to","as a result of"],"wf":[],"ety":"Dari bahasa Latin 'debitus' (terutang), dari 'debere' (berutang). Awalnya hanya digunakan setelah kata benda; penggunaannya sebagai preposisi yang berarti 'karena' meluas pada abad ke-20.","q":"The flight was delayed ___ bad weather conditions at the destination airport."},
{"w":"in accordance with","pos":"phrase","cat":"PHRASE","m":"following the rules of","tr":"sesuai dengan","i":"in a way that follows or obeys something","e":"Please act in accordance with company policy at all times.","s":["following","complying with","as per"],"wf":[],"ety":"Dari bahasa Prancis Kuno 'acorder' (setuju), dari bahasa Latin 'accordare'. Frasa formal yang digunakan dalam penulisan hukum dan bisnis sejak abad ke-15.","q":"All expenses must be submitted ___ the company's reimbursement policy."},
{"w":"in lieu of","pos":"phrase","cat":"PHRASE","m":"instead of","tr":"sebagai pengganti","i":"in place of; as a substitute for","e":"Employees may take time off in lieu of overtime pay.","s":["instead of","in place of","as a substitute for"],"wf":[],"ety":"Dari bahasa Prancis 'lieu' (tempat), dari bahasa Latin 'locus' (tempat). Frasa 'in lieu of' masuk ke bahasa Inggris pada abad ke-16 dari terminologi hukum Prancis.","q":"Staff who work on public holidays may take a day off ___ additional pay."},
{"w":"on behalf of","pos":"phrase","cat":"PHRASE","m":"representing someone","tr":"atas nama / mewakili","i":"as a representative of someone","e":"I am writing on behalf of the entire management team.","s":["representing","for","in the name of"],"wf":[],"ety":"Dari bahasa Inggris Kuno 'be healfe' (di sisi). Frasa modern 'on behalf of' menjadi standar dalam korespondensi bahasa Inggris pada abad ke-15.","q":"I am writing ___ the CEO to inform you of the upcoming changes to our service."},
{"w":"prior to","pos":"phrase","cat":"PHRASE","m":"before","tr":"sebelum","i":"before a particular time or event","e":"Please submit all documents prior to the interview.","s":["before","ahead of","in advance of"],"wf":[],"ety":"Dari bahasa Latin 'prior' (terdahulu, lebih awal). Alternatif formal dari 'before' yang umum dalam penulisan bisnis dan hukum sejak abad ke-18.","q":"All candidates must submit their portfolios ___ the application deadline."},
{"w":"regardless of","pos":"phrase","cat":"PHRASE","m":"without being affected by","tr":"terlepas dari / tanpa memandang","i":"without being influenced by something","e":"All employees are treated equally regardless of their background.","s":["despite","irrespective of","no matter"],"wf":[],"ety":"Dari kata 'regard' (perhatian, pertimbangan) + '-less' (tanpa). Frasa ini menjadi standar dalam bahasa Inggris pada abad ke-19.","q":"All applicants will be considered ___ their age, gender, or nationality."},
{"w":"take effect","pos":"phrase","cat":"PHRASE","m":"to become active","tr":"mulai berlaku","i":"to come into operation; to start working","e":"The new regulations will take effect on the first of next month.","s":["come into force","become active","apply"],"wf":[],"ety":"Dari bahasa Latin 'effectus' (pencapaian), dari 'efficere' (menyelesaikan). Frasa 'take effect' menjadi standar dalam bahasa Inggris hukum dan bisnis pada abad ke-17.","q":"The new pricing structure will ___ from the first day of next quarter."},
{"w":"with regard to","pos":"phrase","cat":"PHRASE","m":"concerning; about","tr":"sehubungan dengan / mengenai","i":"in connection with; concerning","e":"With regard to your inquiry, we will respond within 48 hours.","s":["concerning","regarding","about"],"wf":[],"ety":"Dari bahasa Prancis Kuno 'regarder' (melihat), dari 're-' (kembali) + 'garder' (menjaga). Frasa formal yang digunakan dalam korespondensi bisnis sejak abad ke-15.","q":"___ your recent complaint, we have investigated the matter and taken corrective action."},
{"w":"carry out","pos":"phrase","cat":"PHRASE","m":"to perform or complete","tr":"melaksanakan / menjalankan","i":"to perform or complete a task","e":"The team will carry out a full review of the process.","s":["perform","execute","complete"],"wf":[],"ety":"Frasa kata kerja yang menggabungkan 'carry' (dari bahasa Norse Kuno 'karra') + 'out'. Makna menyelesaikan tugas berkembang pada abad ke-19.","q":"The engineering team will ___ a full inspection of the facility next week."},
{"w":"reach out","pos":"phrase","cat":"PHRASE","m":"to contact someone","tr":"menghubungi","i":"to make contact with someone","e":"Please reach out to our support team if you have any questions.","s":["contact","get in touch","connect"],"wf":[],"ety":"Awalnya tindakan fisik mengulurkan tangan. Makna kiasan menghubungi seseorang menjadi umum dalam bahasa bisnis Amerika pada akhir abad ke-20.","q":"Please ___ to our customer service team if you experience any issues with your order."},
{"w":"set aside","pos":"phrase","cat":"PHRASE","m":"to reserve for a purpose","tr":"menyisihkan / mengalokasikan","i":"to keep something for a specific purpose","e":"We have set aside a portion of the budget for training.","s":["reserve","allocate","save"],"wf":[],"ety":"Frasa kata kerja dari 'set' (bahasa Inggris Kuno 'settan') + 'aside'. Makna menyisihkan sesuatu untuk tujuan tertentu berkembang pada abad ke-17.","q":"The company has ___ $200,000 for employee development programs this year."},
{"w":"up to date","pos":"phrase","cat":"PHRASE","m":"current; modern","tr":"terkini / mutakhir","i":"incorporating the latest information or developments","e":"Please make sure your contact information is up to date.","s":["current","latest","recent"],"wf":[],"ety":"Frasa gabungan dari 'up' + 'to' + 'date'. Makna mengikuti informasi terbaru berkembang pada abad ke-19.","q":"Please ensure that all employee records are ___ before the annual review."},
]

with open("public/games/flashcard_lengkap_intact/toeic_test06_vocab.html", "a", encoding="utf-8") as f:
    for w in rest:
        f.write("  " + json.dumps(w, ensure_ascii=False) + ",\n")
print(f"Written {len(rest)} adj/adv/phrase entries")
