import json

# All 131 words with tr (Indonesian), wf (word family), ety (etymology)
words = [
# ── VERBS ──
{"w":"authorize","pos":"verb","cat":"VERB","m":"to officially approve","tr":"mengizinkan secara resmi","i":"to give official permission for something","e":"Only the manager is authorized to approve expense reports.","s":["approve","permit","sanction"],"wf":[{"w":"authorization","p":"noun"},{"w":"authorized","p":"adj"},{"w":"authority","p":"noun"}],"ety":"From Latin 'auctorizare' (to give authority), from 'auctor' (originator). Entered English via Old French in the 14th century."},
{"w":"consolidate","pos":"verb","cat":"VERB","m":"to combine into one","tr":"menggabungkan menjadi satu","i":"to merge separate things into a single stronger unit","e":"The company plans to consolidate its two offices into one location.","s":["merge","combine","unify"],"wf":[{"w":"consolidation","p":"noun"},{"w":"consolidated","p":"adj"}],"ety":"From Latin 'consolidare' (to make solid), from 'con-' (together) + 'solidus' (solid). Used in English since the 16th century."},
{"w":"retain","pos":"verb","cat":"VERB","m":"to keep or maintain","tr":"mempertahankan","i":"to continue to have something; not to lose it","e":"The company has managed to retain its top employees for over a decade.","s":["keep","maintain","preserve"],"wf":[{"w":"retention","p":"noun"},{"w":"retentive","p":"adj"}],"ety":"From Latin 'retinere' (to hold back), from 're-' (back) + 'tenere' (to hold). Entered English in the 15th century."},
{"w":"revise","pos":"verb","cat":"VERB","m":"to update or correct","tr":"merevisi / memperbaiki","i":"to make changes to improve or correct something","e":"Please revise the proposal before submitting it to the client.","s":["update","amend","edit"],"wf":[{"w":"revision","p":"noun"},{"w":"revised","p":"adj"}],"ety":"From Latin 'revisere' (to look at again), from 're-' (again) + 'videre' (to see). Entered English in the 17th century."},
{"w":"notify","pos":"verb","cat":"VERB","m":"to inform officially","tr":"memberitahukan secara resmi","i":"to formally tell someone about something","e":"Please notify the HR department of any changes to your personal information.","s":["inform","alert","advise"],"wf":[{"w":"notification","p":"noun"},{"w":"notice","p":"noun"}],"ety":"From Latin 'notificare' (to make known), from 'notus' (known) + 'facere' (to make). Used in English since the 15th century."},
{"w":"finalize","pos":"verb","cat":"VERB","m":"to complete the last details","tr":"menyelesaikan tahap akhir","i":"to put the finishing touches on something","e":"We need to finalize the contract before the end of the week.","s":["complete","conclude","settle"],"wf":[{"w":"final","p":"adj"},{"w":"finalization","p":"noun"},{"w":"finally","p":"adv"}],"ety":"From Latin 'finalis' (of the end), from 'finis' (end). The verb form became common in American English in the 20th century."},
{"w":"outsource","pos":"verb","cat":"VERB","m":"to hire externally","tr":"mengalihdayakan","i":"to arrange for work to be done by an outside company","e":"The firm decided to outsource its IT support to a specialist company.","s":["subcontract","delegate","farm out"],"wf":[{"w":"outsourcing","p":"noun"},{"w":"outsourced","p":"adj"}],"ety":"Compound of 'out' + 'source'. Emerged in American business English in the 1980s as companies began contracting work to external providers."},
{"w":"streamline","pos":"verb","cat":"VERB","m":"to make more efficient","tr":"menyederhanakan proses","i":"to simplify a process to make it faster and more effective","e":"The new software will streamline the invoicing process.","s":["simplify","optimize","improve"],"wf":[{"w":"streamlined","p":"adj"},{"w":"streamlining","p":"noun"}],"ety":"Originally a physics term (1860s) for a smooth flow of fluid. Applied to business processes in the 20th century to mean making operations more efficient."},
{"w":"reimburse","pos":"verb","cat":"VERB","m":"to pay back expenses","tr":"mengganti biaya","i":"to repay someone for money they have spent","e":"Submit your receipts and we will reimburse you within five business days.","s":["repay","refund","compensate"],"wf":[{"w":"reimbursement","p":"noun"}],"ety":"From French 'rembourser', from 're-' (back) + 'embourser' (to put in a purse). Entered English in the 17th century."},
{"w":"launch","pos":"verb","cat":"VERB","m":"to introduce publicly","tr":"meluncurkan","i":"to start or introduce a new product, service, or campaign","e":"The company will launch its new product line next quarter.","s":["introduce","release","unveil"],"wf":[{"w":"launch","p":"noun"},{"w":"launcher","p":"noun"}],"ety":"From Old French 'lanchier' (to throw a lance). Originally meant to throw or hurl; evolved to mean starting something new in the 17th century."},
{"w":"negotiate","pos":"verb","cat":"VERB","m":"to discuss to reach agreement","tr":"bernegosiasi","i":"to have formal discussions to reach a mutually acceptable outcome","e":"Both parties agreed to negotiate the terms of the contract.","s":["discuss","bargain","mediate"],"wf":[{"w":"negotiation","p":"noun"},{"w":"negotiator","p":"noun"},{"w":"negotiable","p":"adj"}],"ety":"From Latin 'negotiari' (to carry on business), from 'negotium' (business), from 'nec' (not) + 'otium' (leisure). Entered English in the 16th century."},
{"w":"monitor","pos":"verb","cat":"VERB","m":"to watch and check","tr":"memantau","i":"to regularly observe and check the progress of something","e":"The supervisor will monitor employee performance on a monthly basis.","s":["track","oversee","observe"],"wf":[{"w":"monitoring","p":"noun"},{"w":"monitor","p":"noun"}],"ety":"From Latin 'monitor' (one who warns), from 'monere' (to warn). The verb sense of watching/checking developed in the 20th century."},
{"w":"allocate","pos":"verb","cat":"VERB","m":"to assign resources","tr":"mengalokasikan","i":"to distribute resources or duties for a specific purpose","e":"The budget was allocated equally among all departments.","s":["assign","distribute","designate"],"wf":[{"w":"allocation","p":"noun"},{"w":"allocated","p":"adj"}],"ety":"From Medieval Latin 'allocare' (to place), from 'ad-' (to) + 'locare' (to place). Entered English in the 17th century."},
{"w":"comply","pos":"verb","cat":"VERB","m":"to follow rules","tr":"mematuhi","i":"to act in accordance with rules, regulations, or requests","e":"All staff must comply with the new workplace safety guidelines.","s":["obey","adhere to","conform to"],"wf":[{"w":"compliance","p":"noun"},{"w":"compliant","p":"adj"}],"ety":"From Italian 'complire' (to fulfill), from Latin 'complere' (to fill up). Entered English in the 17th century."},
{"w":"submit","pos":"verb","cat":"VERB","m":"to hand in formally","tr":"mengajukan / menyerahkan","i":"to present a document or application for consideration","e":"Please submit your application before the deadline.","s":["hand in","present","file"],"wf":[{"w":"submission","p":"noun"},{"w":"submitted","p":"adj"}],"ety":"From Latin 'submittere' (to put under), from 'sub-' (under) + 'mittere' (to send). Entered English in the 14th century."},
{"w":"coordinate","pos":"verb","cat":"VERB","m":"to organize jointly","tr":"mengoordinasikan","i":"to organize people or activities so they work together effectively","e":"She was asked to coordinate the annual sales conference.","s":["organize","manage","arrange"],"wf":[{"w":"coordination","p":"noun"},{"w":"coordinator","p":"noun"}],"ety":"From Latin 'coordinare' (to arrange in order), from 'co-' (together) + 'ordinare' (to arrange). Entered English in the 19th century."},
{"w":"evaluate","pos":"verb","cat":"VERB","m":"to assess carefully","tr":"mengevaluasi","i":"to judge or calculate the quality or value of something","e":"The committee will evaluate all proposals by Friday.","s":["assess","review","appraise"],"wf":[{"w":"evaluation","p":"noun"},{"w":"evaluator","p":"noun"}],"ety":"From French 'evaluer', from 'e-' (out) + 'valuer' (to value), from Latin 'valere' (to be worth). Entered English in the 19th century."},
{"w":"implement","pos":"verb","cat":"VERB","m":"to put into action","tr":"menerapkan / melaksanakan","i":"to put a plan or decision into effect","e":"The new policy will be implemented starting next month.","s":["execute","apply","carry out"],"wf":[{"w":"implementation","p":"noun"},{"w":"implementer","p":"noun"}],"ety":"From Latin 'implementum' (a filling up), from 'implere' (to fill). Originally meant a tool or instrument; the verb sense of carrying out a plan emerged in the 20th century."},
{"w":"verify","pos":"verb","cat":"VERB","m":"to confirm accuracy","tr":"memverifikasi","i":"to make sure that something is true or correct","e":"Please verify your contact details before submitting the form.","s":["confirm","validate","check"],"wf":[{"w":"verification","p":"noun"},{"w":"verifiable","p":"adj"}],"ety":"From Latin 'verificare' (to make true), from 'verus' (true) + 'facere' (to make). Entered English in the 14th century."},
{"w":"expedite","pos":"verb","cat":"VERB","m":"to speed up","tr":"mempercepat proses","i":"to make a process happen more quickly","e":"We need to expedite the shipment to meet the client deadline.","s":["accelerate","rush","fast-track"],"wf":[{"w":"expeditious","p":"adj"},{"w":"expeditiously","p":"adv"}],"ety":"From Latin 'expedire' (to free the feet), from 'ex-' (out) + 'pes/pedis' (foot). Originally meant to free from obstacles; evolved to mean speeding up in the 17th century."},
{"w":"postpone","pos":"verb","cat":"VERB","m":"to delay to a later time","tr":"menunda","i":"to arrange for something to happen at a later time than planned","e":"The board meeting has been postponed until further notice.","s":["delay","defer","reschedule"],"wf":[{"w":"postponement","p":"noun"},{"w":"postponed","p":"adj"}],"ety":"From Latin 'postponere' (to put after), from 'post-' (after) + 'ponere' (to place). Entered English in the 16th century."},
{"w":"acquire","pos":"verb","cat":"VERB","m":"to obtain or buy","tr":"memperoleh / mengakuisisi","i":"to gain possession of something, especially through effort or purchase","e":"The company acquired a smaller competitor last year.","s":["obtain","purchase","gain"],"wf":[{"w":"acquisition","p":"noun"},{"w":"acquired","p":"adj"}],"ety":"From Latin 'acquirere' (to seek in addition), from 'ad-' (to) + 'quaerere' (to seek). Entered English in the 15th century."},
{"w":"distribute","pos":"verb","cat":"VERB","m":"to hand out or deliver","tr":"mendistribusikan","i":"to give or deliver something to a number of people","e":"The marketing team will distribute flyers at the trade show.","s":["deliver","hand out","circulate"],"wf":[{"w":"distribution","p":"noun"},{"w":"distributor","p":"noun"}],"ety":"From Latin 'distribuere' (to divide), from 'dis-' (apart) + 'tribuere' (to assign). Entered English in the 15th century."},
{"w":"renovate","pos":"verb","cat":"VERB","m":"to repair and improve","tr":"merenovasi","i":"to repair and improve a building or room","e":"The office will be renovated over the summer break.","s":["refurbish","restore","remodel"],"wf":[{"w":"renovation","p":"noun"},{"w":"renovated","p":"adj"}],"ety":"From Latin 'renovare' (to renew), from 're-' (again) + 'novare' (to make new), from 'novus' (new). Entered English in the 17th century."},
{"w":"register","pos":"verb","cat":"VERB","m":"to sign up officially","tr":"mendaftar","i":"to put your name on an official list","e":"You must register for the seminar at least two weeks in advance.","s":["sign up","enroll","record"],"wf":[{"w":"registration","p":"noun"},{"w":"registered","p":"adj"},{"w":"registry","p":"noun"}],"ety":"From Medieval Latin 'registrare' (to record), from 'registrum' (a list). Entered English in the 14th century."},
{"w":"facilitate","pos":"verb","cat":"VERB","m":"to make easier","tr":"memudahkan / memfasilitasi","i":"to make a process or action easier or more achievable","e":"The new platform will facilitate communication between teams.","s":["enable","support","assist"],"wf":[{"w":"facilitation","p":"noun"},{"w":"facilitator","p":"noun"}],"ety":"From Latin 'facilis' (easy), from 'facere' (to do). The verb form entered English in the 17th century."},
{"w":"highlight","pos":"verb","cat":"VERB","m":"to draw attention to","tr":"menonjolkan / menyoroti","i":"to emphasize something as important","e":"The report highlights the need for better data security.","s":["emphasize","feature","showcase"],"wf":[{"w":"highlight","p":"noun"},{"w":"highlighted","p":"adj"}],"ety":"Compound of 'high' + 'light'. Originally a painting term for the brightest part of a picture; the figurative sense of emphasizing emerged in the 20th century."},
{"w":"generate","pos":"verb","cat":"VERB","m":"to produce or create","tr":"menghasilkan","i":"to cause something to exist or occur","e":"The campaign generated significant interest from potential investors.","s":["produce","create","yield"],"wf":[{"w":"generation","p":"noun"},{"w":"generator","p":"noun"}],"ety":"From Latin 'generare' (to beget), from 'genus' (race, kind). Entered English in the 16th century."},
{"w":"enhance","pos":"verb","cat":"VERB","m":"to improve quality","tr":"meningkatkan kualitas","i":"to increase or improve the quality, value, or extent of something","e":"The upgrade will enhance the performance of the entire system.","s":["improve","boost","strengthen"],"wf":[{"w":"enhancement","p":"noun"},{"w":"enhanced","p":"adj"}],"ety":"From Old French 'enhaucier' (to raise), from Latin 'in-' (in) + 'altus' (high). Entered English in the 13th century."},
{"w":"anticipate","pos":"verb","cat":"VERB","m":"to expect in advance","tr":"mengantisipasi / memperkirakan","i":"to expect or predict something before it happens","e":"We anticipate strong demand for the new product.","s":["expect","foresee","predict"],"wf":[{"w":"anticipation","p":"noun"},{"w":"anticipated","p":"adj"}],"ety":"From Latin 'anticipare' (to take before), from 'ante-' (before) + 'capere' (to take). Entered English in the 16th century."},
{"w":"accommodate","pos":"verb","cat":"VERB","m":"to provide space or adjust","tr":"menampung / mengakomodasi","i":"to provide room for, or to adjust to meet needs","e":"The conference hall can accommodate up to 500 guests.","s":["house","hold","cater for"],"wf":[{"w":"accommodation","p":"noun"},{"w":"accommodating","p":"adj"}],"ety":"From Latin 'accommodare' (to make fit), from 'ad-' (to) + 'commodus' (fitting). Entered English in the 16th century."},
{"w":"demonstrate","pos":"verb","cat":"VERB","m":"to show clearly","tr":"mendemonstrasikan","i":"to show or prove something clearly","e":"The results demonstrate the effectiveness of the new approach.","s":["show","prove","illustrate"],"wf":[{"w":"demonstration","p":"noun"},{"w":"demonstrative","p":"adj"}],"ety":"From Latin 'demonstrare' (to point out), from 'de-' (completely) + 'monstrare' (to show). Entered English in the 16th century."},
{"w":"collaborate","pos":"verb","cat":"VERB","m":"to work together","tr":"berkolaborasi","i":"to work jointly with others on a project","e":"The two departments will collaborate on the new marketing campaign.","s":["cooperate","partner","team up"],"wf":[{"w":"collaboration","p":"noun"},{"w":"collaborative","p":"adj"},{"w":"collaborator","p":"noun"}],"ety":"From Latin 'collaborare' (to labor together), from 'col-' (together) + 'laborare' (to work). Entered English in the 19th century."},
{"w":"investigate","pos":"verb","cat":"VERB","m":"to examine thoroughly","tr":"menyelidiki","i":"to carry out a systematic inquiry into something","e":"The auditors were asked to investigate the financial discrepancy.","s":["examine","probe","look into"],"wf":[{"w":"investigation","p":"noun"},{"w":"investigator","p":"noun"}],"ety":"From Latin 'investigare' (to track), from 'in-' (in) + 'vestigare' (to track), from 'vestigium' (footprint). Entered English in the 16th century."},
{"w":"propose","pos":"verb","cat":"VERB","m":"to suggest formally","tr":"mengusulkan","i":"to put forward a plan or idea for consideration","e":"The manager proposed a new approach to customer service.","s":["suggest","recommend","put forward"],"wf":[{"w":"proposal","p":"noun"},{"w":"proposition","p":"noun"}],"ety":"From Latin 'proponere' (to put forward), from 'pro-' (forward) + 'ponere' (to place). Entered English in the 14th century."},
]

with open("public/games/flashcard_lengkap_intact/toeic_test06_vocab.html", "a", encoding="utf-8") as f:
    for w in words:
        f.write("  " + json.dumps(w, ensure_ascii=False) + ",\n")

print(f"Written {len(words)} verbs")
