import json

adj_adv_phrase = [
# ── ADJECTIVES ──
{"w":"adequate","pos":"adj","cat":"ADJ","m":"enough; satisfactory","tr":"memadai / cukup","i":"sufficient for a specific need or requirement","e":"Make sure the budget is adequate to cover all project costs.","s":["sufficient","enough","satisfactory"],"wf":[{"w":"adequacy","p":"noun"},{"w":"adequately","p":"adv"}],"ety":"From Latin 'adaequatus' (made equal to), from 'ad-' (to) + 'aequare' (to make equal). Entered English in the 17th century."},
{"w":"comprehensive","pos":"adj","cat":"ADJ","m":"covering everything","tr":"komprehensif / menyeluruh","i":"including all or nearly all elements or aspects","e":"The report provides a comprehensive overview of market trends.","s":["thorough","complete","extensive"],"wf":[{"w":"comprehend","p":"verb"},{"w":"comprehension","p":"noun"},{"w":"comprehensively","p":"adv"}],"ety":"From Latin 'comprehensivus', from 'comprehendere' (to grasp), from 'com-' (together) + 'prehendere' (to seize). Entered English in the 17th century."},
{"w":"confidential","pos":"adj","cat":"ADJ","m":"private; secret","tr":"rahasia / bersifat rahasia","i":"intended to be kept secret","e":"All client information must be treated as confidential.","s":["private","classified","restricted"],"wf":[{"w":"confidence","p":"noun"},{"w":"confidentially","p":"adv"},{"w":"confidentiality","p":"noun"}],"ety":"From Latin 'confidentia' (trust), from 'confidere' (to trust fully). The sense of secrecy developed in the 18th century."},
{"w":"consecutive","pos":"adj","cat":"ADJ","m":"following in order","tr":"berturut-turut","i":"following each other continuously without interruption","e":"The company has reported profits for five consecutive quarters.","s":["successive","continuous","sequential"],"wf":[{"w":"consecutively","p":"adv"},{"w":"consecutiveness","p":"noun"}],"ety":"From Latin 'consecutivus', from 'consequi' (to follow), from 'con-' (together) + 'sequi' (to follow). Entered English in the 17th century."},
{"w":"dedicated","pos":"adj","cat":"ADJ","m":"committed to a purpose","tr":"berdedikasi / berkomitmen","i":"devoted to a task or purpose","e":"She is a dedicated employee who always goes above and beyond.","s":["committed","devoted","hardworking"],"wf":[{"w":"dedicate","p":"verb"},{"w":"dedication","p":"noun"}],"ety":"From Latin 'dedicare' (to devote), from 'de-' (completely) + 'dicare' (to proclaim). Entered English in the 15th century."},
{"w":"eligible","pos":"adj","cat":"ADJ","m":"qualified to receive","tr":"memenuhi syarat / berhak","i":"satisfying the conditions required to receive something","e":"Employees who have worked for two years are eligible for the bonus.","s":["qualified","entitled","suitable"],"wf":[{"w":"eligibility","p":"noun"},{"w":"ineligible","p":"adj (opposite)"}],"ety":"From Latin 'eligibilis' (that may be chosen), from 'eligere' (to choose), from 'e-' (out) + 'legere' (to pick). Entered English in the 15th century."},
{"w":"flexible","pos":"adj","cat":"ADJ","m":"able to adapt easily","tr":"fleksibel / mudah menyesuaikan diri","i":"willing to change or compromise","e":"We offer flexible working hours to all full-time employees.","s":["adaptable","versatile","adjustable"],"wf":[{"w":"flexibility","p":"noun"},{"w":"flexibly","p":"adv"},{"w":"inflexible","p":"adj (opposite)"}],"ety":"From Latin 'flexibilis' (that may be bent), from 'flectere' (to bend). Entered English in the 16th century."},
{"w":"mandatory","pos":"adj","cat":"ADJ","m":"required by law or rules","tr":"wajib / diwajibkan","i":"required by law or rules; compulsory","e":"Attendance at the safety briefing is mandatory for all new staff.","s":["compulsory","required","obligatory"],"wf":[{"w":"mandate","p":"noun/verb"},{"w":"mandatorily","p":"adv"}],"ety":"From Late Latin 'mandatorius', from 'mandatum' (a command), from 'mandare' (to command). Entered English in the 18th century."},
{"w":"outstanding","pos":"adj","cat":"ADJ","m":"excellent; unpaid","tr":"luar biasa / belum dibayar","i":"exceptionally good; or not yet paid or resolved","e":"She received an award for her outstanding contribution to the team.","s":["excellent","exceptional","remarkable"],"wf":[{"w":"outstandingly","p":"adv"}],"ety":"Compound of 'out-' + 'standing'. Originally meant 'projecting outward'; the sense of 'unpaid' developed in the 17th century, and 'excellent' in the 19th century."},
{"w":"preliminary","pos":"adj","cat":"ADJ","m":"done before the main event","tr":"pendahuluan / awal","i":"coming before a more important action or event","e":"The preliminary results suggest the campaign was a success.","s":["initial","preparatory","introductory"],"wf":[{"w":"preliminary","p":"noun"},{"w":"preliminarily","p":"adv"}],"ety":"From Modern Latin 'praeliminaris', from 'prae-' (before) + 'limen' (threshold). Entered English in the 17th century."},
{"w":"profitable","pos":"adj","cat":"ADJ","m":"generating financial gain","tr":"menguntungkan","i":"yielding profit or financial gain","e":"The new product line has been highly profitable.","s":["lucrative","rewarding","successful"],"wf":[{"w":"profit","p":"noun/verb"},{"w":"profitably","p":"adv"},{"w":"profitability","p":"noun"}],"ety":"From Old French 'profitable', from 'profiter' (to benefit), from Latin 'profectus' (progress). Entered English in the 14th century."},
{"w":"qualified","pos":"adj","cat":"ADJ","m":"having the right skills","tr":"berkualifikasi / memenuhi syarat","i":"officially recognized as having the necessary skills","e":"We are looking for a qualified accountant to join our team.","s":["certified","trained","competent"],"wf":[{"w":"qualify","p":"verb"},{"w":"qualification","p":"noun"},{"w":"qualifier","p":"noun"}],"ety":"From Medieval Latin 'qualificare' (to attribute a quality to), from 'qualis' (of what kind) + 'facere' (to make). Entered English in the 16th century."},
{"w":"reliable","pos":"adj","cat":"ADJ","m":"consistently dependable","tr":"dapat diandalkan","i":"consistently good in quality or performance","e":"We need a reliable supplier who can meet our deadlines.","s":["dependable","trustworthy","consistent"],"wf":[{"w":"rely","p":"verb"},{"w":"reliability","p":"noun"},{"w":"reliably","p":"adv"}],"ety":"From French 'relier' (to bind together), from Latin 'religare' (to bind back). The sense of trustworthiness developed in the 19th century."},
{"w":"substantial","pos":"adj","cat":"ADJ","m":"large in size or amount","tr":"substansial / cukup besar","i":"of considerable importance, size, or worth","e":"The company made a substantial investment in new technology.","s":["significant","considerable","large"],"wf":[{"w":"substance","p":"noun"},{"w":"substantially","p":"adv"}],"ety":"From Latin 'substantialis' (having substance), from 'substantia' (substance). Entered English in the 14th century."},
{"w":"supplemental","pos":"adj","cat":"ADJ","m":"added to complete","tr":"tambahan / pelengkap","i":"provided in addition to what already exists","e":"The supplemental report contains additional financial data.","s":["additional","extra","complementary"],"wf":[{"w":"supplement","p":"noun/verb"},{"w":"supplementary","p":"adj"}],"ety":"From Latin 'supplementum' (a filling up), from 'supplere' (to fill up), from 'sub-' (under) + 'plere' (to fill). Entered English in the 17th century."},
{"w":"temporary","pos":"adj","cat":"ADJ","m":"lasting for a short time","tr":"sementara","i":"lasting for only a limited period of time","e":"The road closure is temporary and will last about two weeks.","s":["short-term","interim","provisional"],"wf":[{"w":"temporarily","p":"adv"},{"w":"temporariness","p":"noun"}],"ety":"From Latin 'temporarius' (of the seasons), from 'tempus' (time). Entered English in the 16th century."},
{"w":"unanimous","pos":"adj","cat":"ADJ","m":"agreed by everyone","tr":"bulat / mufakat","i":"fully agreed by all people involved","e":"The board reached a unanimous decision to approve the merger.","s":["agreed","united","undivided"],"wf":[{"w":"unanimously","p":"adv"},{"w":"unanimity","p":"noun"}],"ety":"From Latin 'unanimus' (of one mind), from 'unus' (one) + 'animus' (mind). Entered English in the 17th century."},
{"w":"urgent","pos":"adj","cat":"ADJ","m":"requiring immediate action","tr":"mendesak","i":"requiring immediate action or attention","e":"Please respond to this urgent request as soon as possible.","s":["pressing","critical","immediate"],"wf":[{"w":"urge","p":"verb"},{"w":"urgency","p":"noun"},{"w":"urgently","p":"adv"}],"ety":"From Latin 'urgens' (pressing), from 'urgere' (to press, drive). Entered English in the 16th century."},
{"w":"valid","pos":"adj","cat":"ADJ","m":"legally or officially acceptable","tr":"sah / berlaku","i":"legally or officially acceptable","e":"Your parking permit is valid for 30 days from the date of issue.","s":["legitimate","acceptable","current"],"wf":[{"w":"validate","p":"verb"},{"w":"validity","p":"noun"},{"w":"validation","p":"noun"}],"ety":"From Latin 'validus' (strong, effective), from 'valere' (to be strong). Entered English in the 16th century."},
# ── ADVERBS ──
{"w":"accordingly","pos":"adv","cat":"ADV","m":"in a way that is appropriate","tr":"dengan demikian / sesuai","i":"in a way that is appropriate to the circumstances","e":"Please review the updated guidelines and act accordingly.","s":["appropriately","correspondingly","therefore"],"wf":[{"w":"accord","p":"noun/verb"},{"w":"according","p":"prep"}],"ety":"From 'accord' (agreement), from Old French 'acorder', from Latin 'accordare' (to be of one heart). The adverb form entered English in the 15th century."},
{"w":"approximately","pos":"adv","cat":"ADV","m":"roughly; about","tr":"kira-kira / sekitar","i":"used to show that something is not exact","e":"The project will take approximately three months to complete.","s":["roughly","about","around"],"wf":[{"w":"approximate","p":"adj/verb"},{"w":"approximation","p":"noun"}],"ety":"From Latin 'approximare' (to come near to), from 'ad-' (to) + 'proximus' (nearest). Entered English in the 17th century."},
{"w":"consistently","pos":"adv","cat":"ADV","m":"in the same way always","tr":"secara konsisten","i":"in every case or on every occasion; always","e":"She has consistently exceeded her sales targets.","s":["always","regularly","constantly"],"wf":[{"w":"consistent","p":"adj"},{"w":"consistency","p":"noun"}],"ety":"From Latin 'consistere' (to stand firm), from 'con-' (together) + 'sistere' (to stand). Entered English in the 17th century."},
{"w":"efficiently","pos":"adv","cat":"ADV","m":"in a productive way","tr":"secara efisien","i":"in a way that achieves maximum productivity with minimum waste","e":"The new system processes orders more efficiently.","s":["productively","effectively","smoothly"],"wf":[{"w":"efficient","p":"adj"},{"w":"efficiency","p":"noun"}],"ety":"From Latin 'efficientem' (effective), from 'efficere' (to accomplish), from 'ex-' (out) + 'facere' (to do). Entered English in the 17th century."},
{"w":"immediately","pos":"adv","cat":"ADV","m":"right away","tr":"segera / langsung","i":"at once; without delay","e":"Please contact the IT department immediately if you notice any issues.","s":["instantly","at once","right away"],"wf":[{"w":"immediate","p":"adj"},{"w":"immediacy","p":"noun"}],"ety":"From Medieval Latin 'immediatus' (without anything between), from 'in-' (not) + 'mediatus' (in the middle). Entered English in the 16th century."},
{"w":"initially","pos":"adv","cat":"ADV","m":"at the beginning","tr":"pada awalnya","i":"at the beginning; at first","e":"The project was initially expected to take six months.","s":["at first","originally","at the start"],"wf":[{"w":"initial","p":"adj/noun"},{"w":"initiate","p":"verb"}],"ety":"From Latin 'initialis' (of the beginning), from 'initium' (beginning), from 'inire' (to go in). Entered English in the 17th century."},
{"w":"promptly","pos":"adv","cat":"ADV","m":"quickly and on time","tr":"dengan segera / tepat waktu","i":"with little or no delay; punctually","e":"Please respond to customer inquiries promptly.","s":["quickly","immediately","without delay"],"wf":[{"w":"prompt","p":"adj/verb"},{"w":"promptness","p":"noun"}],"ety":"From Latin 'promptus' (ready, at hand), from 'promere' (to bring forth). Entered English in the 15th century."},
{"w":"significantly","pos":"adv","cat":"ADV","m":"by a large amount","tr":"secara signifikan","i":"in a sufficiently great or important way","e":"Sales have increased significantly since the new campaign launched.","s":["considerably","substantially","greatly"],"wf":[{"w":"significant","p":"adj"},{"w":"significance","p":"noun"}],"ety":"From Latin 'significare' (to indicate), from 'signum' (sign) + 'facere' (to make). Entered English in the 16th century."},
{"w":"temporarily","pos":"adv","cat":"ADV","m":"for a limited time","tr":"untuk sementara","i":"for a limited period of time; not permanently","e":"The office will be temporarily closed for renovations.","s":["briefly","for now","short-term"],"wf":[{"w":"temporary","p":"adj"},{"w":"temporariness","p":"noun"}],"ety":"From Latin 'temporarius' (of the seasons). The adverb form entered English in the 17th century."},
{"w":"thoroughly","pos":"adv","cat":"ADV","m":"completely and carefully","tr":"secara menyeluruh","i":"in a thorough manner; completely","e":"Please review the document thoroughly before signing.","s":["completely","carefully","fully"],"wf":[{"w":"thorough","p":"adj"},{"w":"thoroughness","p":"noun"}],"ety":"From Old English 'thuruh' (through). Originally meant 'from end to end'; the sense of doing something completely developed in the 14th century."},
# ── PHRASES ──
{"w":"as of","pos":"phrase","cat":"PHRASE","m":"starting from a date","tr":"terhitung mulai / per tanggal","i":"used to indicate the time or date from which something applies","e":"As of January 1, all employees must use the new system.","s":["starting from","effective","beginning"],"wf":[],"ety":"American English phrase that became standard in business writing in the 20th century. Indicates the effective date of a change or policy."},
{"w":"at your earliest convenience","pos":"phrase","cat":"PHRASE","m":"as soon as possible","tr":"sesegera mungkin","i":"used to politely ask someone to do something soon","e":"Please contact us at your earliest convenience.","s":["as soon as possible","when you can","promptly"],"wf":[],"ety":"A formal business phrase that softens a request for urgency. Common in professional correspondence since the 19th century."},
{"w":"be subject to","pos":"phrase","cat":"PHRASE","m":"dependent on conditions","tr":"tunduk pada / bergantung pada","i":"likely to be affected by or dependent on something","e":"All prices are subject to change without notice.","s":["dependent on","conditional on","liable to"],"wf":[],"ety":"From Latin 'subjectus' (placed under), from 'sub-' (under) + 'jacere' (to throw). The phrase became standard in legal and business English in the 18th century."},
{"w":"due to","pos":"phrase","cat":"PHRASE","m":"because of","tr":"karena / disebabkan oleh","i":"as a result of; caused by","e":"The meeting was cancelled due to a scheduling conflict.","s":["because of","owing to","as a result of"],"wf":[],"ety":"From Latin 'debitus' (owed), from 'debere' (to owe). Originally used only after a noun; its use as a preposition meaning 'because of' became widespread in the 20th century."},
{"w":"in accordance with","pos":"phrase","cat":"PHRASE","m":"following the rules of","tr":"sesuai dengan","i":"in a way that follows or obeys something","e":"Please act in accordance with company policy at all times.","s":["following","complying with","as per"],"wf":[],"ety":"From Old French 'acorder' (to agree), from Latin 'accordare'. A formal phrase used in legal and business writing since the 15th century."},
{"w":"in lieu of","pos":"phrase","cat":"PHRASE","m":"instead of","tr":"sebagai pengganti","i":"in place of; as a substitute for","e":"Employees may take time off in lieu of overtime pay.","s":["instead of","in place of","as a substitute for"],"wf":[],"ety":"From French 'lieu' (place), from Latin 'locus' (place). The phrase 'in lieu of' entered English in the 16th century from French legal terminology."},
{"w":"on behalf of","pos":"phrase","cat":"PHRASE","m":"representing someone","tr":"atas nama / mewakili","i":"as a representative of someone","e":"I am writing on behalf of the entire management team.","s":["representing","for","in the name of"],"wf":[],"ety":"From Old English 'be healfe' (by the side of). The modern phrase 'on behalf of' became standard in English correspondence in the 15th century."},
{"w":"prior to","pos":"phrase","cat":"PHRASE","m":"before","tr":"sebelum","i":"before a particular time or event","e":"Please submit all documents prior to the interview.","s":["before","ahead of","in advance of"],"wf":[],"ety":"From Latin 'prior' (former, earlier). A formal alternative to 'before' that became common in business and legal writing in the 18th century."},
{"w":"regardless of","pos":"phrase","cat":"PHRASE","m":"without being affected by","tr":"terlepas dari / tanpa memandang","i":"without being influenced by something","e":"All employees are treated equally regardless of their background.","s":["despite","irrespective of","no matter"],"wf":[],"ety":"From 'regard' (attention, consideration) + '-less' (without). The phrase became standard in English in the 19th century."},
{"w":"take effect","pos":"phrase","cat":"PHRASE","m":"to become active","tr":"mulai berlaku","i":"to come into operation; to start working","e":"The new regulations will take effect on the first of next month.","s":["come into force","become active","apply"],"wf":[],"ety":"From Latin 'effectus' (accomplishment), from 'efficere' (to accomplish). The phrase 'take effect' became standard in legal and business English in the 17th century."},
{"w":"with regard to","pos":"phrase","cat":"PHRASE","m":"concerning; about","tr":"sehubungan dengan / mengenai","i":"in connection with; concerning","e":"With regard to your inquiry, we will respond within 48 hours.","s":["concerning","regarding","about"],"wf":[],"ety":"From Old French 'regarder' (to look at), from 're-' (back) + 'garder' (to guard). A formal phrase used in business correspondence since the 15th century."},
{"w":"carry out","pos":"phrase","cat":"PHRASE","m":"to perform or complete","tr":"melaksanakan / menjalankan","i":"to perform or complete a task","e":"The team will carry out a full review of the process.","s":["perform","execute","complete"],"wf":[],"ety":"Phrasal verb combining 'carry' (from Old Norse 'karra') + 'out'. The sense of completing a task developed in the 19th century."},
{"w":"reach out","pos":"phrase","cat":"PHRASE","m":"to contact someone","tr":"menghubungi","i":"to make contact with someone","e":"Please reach out to our support team if you have any questions.","s":["contact","get in touch","connect"],"wf":[],"ety":"Originally a physical action of extending one's arm. The figurative sense of making contact with someone became common in American business English in the late 20th century."},
{"w":"set aside","pos":"phrase","cat":"PHRASE","m":"to reserve for a purpose","tr":"menyisihkan / mengalokasikan","i":"to keep something for a specific purpose","e":"We have set aside a portion of the budget for training.","s":["reserve","allocate","save"],"wf":[],"ety":"Phrasal verb from 'set' (Old English 'settan') + 'aside'. The sense of reserving something for a specific purpose developed in the 17th century."},
{"w":"up to date","pos":"phrase","cat":"PHRASE","m":"current; modern","tr":"terkini / mutakhir","i":"incorporating the latest information or developments","e":"Please make sure your contact information is up to date.","s":["current","latest","recent"],"wf":[],"ety":"Compound phrase from 'up' + 'to' + 'date'. The sense of being current with the latest information developed in the 19th century."},
]

with open("public/games/flashcard_lengkap_intact/toeic_test06_vocab.html", "a", encoding="utf-8") as f:
    for w in adj_adv_phrase:
        f.write("  " + json.dumps(w, ensure_ascii=False) + ",\n")

print(f"Written {len(adj_adv_phrase)} adj/adv/phrase entries")
