import re

content = open("public/games/flashcard_lengkap_intact/flashcard_lengkap_intact.html", encoding="utf-8").read()

# Dictionary: Chinese word -> English meaning
translations = {
    # L2
    "上班": "to go to work",
    "下班": "to get off work; to finish work",
    "回家": "to go home",
    "煮飯": "to cook rice; to cook",
    "吃飯": "to eat; to have a meal",
    "吃早餐": "to eat breakfast",
    "吃午餐": "to eat lunch",
    "吃晚餐": "to eat dinner",
    "出去玩": "to go out and play; to hang out",
    "看電影": "to watch a movie",
    "打電動": "to play video games",
    "上課": "to attend class",
    "下課": "class is dismissed; class ends",
    "睡覺": "to sleep; to go to bed",
    # L3
    "書": "book",
    "兩": "two (for quantities)",
    "本": "measure word for books",
    "中文": "Chinese language; Mandarin",
    "英文": "English language",
    "一些": "some; a few",
    "花": "flower",
    "朵": "measure word for flowers",
    "和": "and",
    "蛋糕": "cake",
    "蛋": "egg",
    "一起": "together",
    "這/這個": "this",
    "那/那個": "that",
    "種": "kind; type; sort",
    "鉛筆": "pencil",
    "筆": "pen",
    "怎麼樣": "how about it? what do you think?",
    "東西": "thing; stuff; item",
    "支": "measure word for pens/pencils",
    "塊": "measure word for money; piece",
    "錢": "money",
    "元": "yuan (currency unit)",
    "顏色": "color",
    "紅色": "red color",
    "白色": "white color",
    "白": "white",
    "都": "all; both",
    "好看": "good-looking; nice",
    "常": "often; frequently",
    # L4
    "還是": "or (in questions)",
    "天氣": "weather",
    "冷": "cold",
    "飲料": "beverage; drink",
    "也": "also; too",
    "餓": "hungry",
    "渴": "thirsty",
    "一點兒": "a little; a bit",
    "餐廳": "restaurant",
    "飯館": "restaurant; eatery",
    "點": "to order (food/drink)",
    "碗": "bowl; measure word for bowls",
    "杯": "cup; glass; measure word for cups",
    "杯子": "cup; glass",
    "瓶子": "bottle",
    "瓶": "bottle; measure word for bottles",
    "女": "female; woman",
    "男": "male; man",
    "位": "polite measure word for people",
    "紅茶": "black tea",
    "綠茶": "green tea",
    "牛奶": "milk",
    "有的": "some (of them)",
    "每": "every; each",
    "天": "day; sky",
    "夏天": "summer",
    "秋天": "autumn; fall",
    "冬天": "winter",
    "店/商店": "shop; store",
    # L5
    "在": "to be at; located at",
    "哪裡/哪兒": "where",
    "聽": "to listen; to hear",
    "下午茶": "afternoon tea",
    "咖啡廳": "café; coffee shop",
    "那裡/那兒": "there; over there",
    "這裡/這兒": "here",
    "冰淇淋": "ice cream",
    "巧克力": "chocolate",
    "半": "half",
    "沒有空": "to have no free time; to be busy",
    "房間": "room",
    "間": "measure word for rooms",
    "房子": "house; building",
    "棟": "measure word for buildings",
    "裡面": "inside",
    "外面": "outside",
    "客廳": "living room",
    "桌子": "table; desk",
    "椅子": "chair",
    "張": "measure word for tables/chairs/paper",
    "哥哥": "older brother",
    "姐姐": "older sister",
    "弟弟": "younger brother",
    "妹妹": "younger sister",
    "沙發": "sofa; couch",
    "廚房": "kitchen",
    "床": "bed",
    "家具": "furniture",
    "電視": "television; TV",
    "台": "measure word for TV/computer/machine",
    "窗戶": "window",
    "門": "door",
    "貓": "cat",
    "狗": "dog",
    "鳥": "bird",
    "隻": "measure word for animals",
    # L6
    "唱歌": "to sing",
    "學": "to learn; to study",
    "學習": "to study; to learn",
    "平常": "usually; normally",
    "有的時候": "sometimes",
    "歌": "song",
    "比賽": "competition; match",
    "畫": "painting; picture",
    "畫畫": "to draw; to paint",
    "真的": "really; truly",
    "興趣": "interest; hobby",
    "跳舞": "to dance",
    "上網": "to go online; to surf the internet",
    "不要": "don't; do not",
    "前天": "the day before yesterday",
    "只": "only; just",
    "後天": "the day after tomorrow",
    "應該": "should; ought to",
    "有一點兒": "a little; somewhat",
    "有趣": "interesting; fun",
    "首": "measure word for songs",
    "高興": "happy; glad",
    "腳踏車/自行車": "bicycle",
    "輛": "measure word for vehicles",
    "部": "measure word for films",
    "電影": "movie; film",
    "電影院": "cinema; movie theater",
    "騎": "to ride (bicycle/horse)",
    "山": "mountain",
    "得": "complement particle (degree)",
    "打": "to play (sports); to hit",
    "棒球": "baseball",
    "海": "sea; ocean",
    "球": "ball",
    "籃球": "basketball",
    "說": "to say; to speak",
    "說話": "to speak; to talk",
    "足球": "soccer; football",
    "跑": "to run",
    "跑步": "to run; jogging",
    "踢": "to kick",
    "風景": "scenery; landscape",
    # L7
    "超級市場": "supermarket",
    "超市": "supermarket (short form)",
    "市場": "market",
    "一定": "definitely; certainly",
    "又": "also; both...and...",
    "方便": "convenient; easy",
    "舒服": "comfortable; feeling well",
    "線": "line; route",
    "藍": "blue",
    "藍色": "blue color",
    "機場": "airport",
    "飛機場": "airport",
    "開車": "to drive a car",
    "司機": "driver",
    "計程車": "taxi",
    "捷運": "MRT; metro",
    "公車": "bus",
    "火車": "train",
    "飛機": "airplane",
    "船": "boat; ship",
    "腳踏車": "bicycle",
    "摩托車": "motorcycle",
    "站": "station; stop",
    "路": "road; street",
    "左": "left",
    "右": "right",
    "直走": "go straight",
    "轉": "to turn",
    "過": "to pass; to cross",
    "紅綠燈": "traffic light",
    "地圖": "map",
    "附近": "nearby; in the vicinity",
    "遠": "far; distant",
    "近": "near; close",
    "走路": "to walk",
    "騎車": "to ride a bike",
    "坐": "to sit; to take (transport)",
    # L8
    "百貨公司": "department store",
    "樓": "floor; story (of a building)",
    "男生": "boy; male student",
    "雜誌": "magazine",
    "舊": "old; used; worn",
    "最新": "newest; latest",
}

# Find all cards missing e field
missing_pattern = re.compile(r"(\{z:'([^']+)',p:'([^']+)',i:'([^']+)',l:'(L[2-8])'\})")
matches = list(missing_pattern.finditer(content))
print(f"Found {len(matches)} cards missing e field")

fixed = 0
not_found = []
new_content = content

for m in matches:
    full_match = m.group(1)
    zh = m.group(2)
    
    if zh in translations:
        eng = translations[zh]
        replacement = full_match.replace(
            f",l:'{m.group(5)}'}}",
            f",l:'{m.group(5)}',e:'{eng}'}}"
        )
        new_content = new_content.replace(full_match, replacement, 1)
        fixed += 1
    else:
        not_found.append(f"{m.group(5)}: {zh} = {m.group(4)}")

print(f"Fixed: {fixed}")
print(f"Not found in dict: {len(not_found)}")
for nf in not_found:
    print(f"  {nf}")

with open("public/games/flashcard_lengkap_intact/flashcard_lengkap_intact.html", "w", encoding="utf-8") as f:
    f.write(new_content)
print("Saved")
