import json

nouns = [
{"w":"agenda","pos":"noun","cat":"NOUN","m":"list of meeting topics","tr":"agenda / daftar topik rapat","i":"a list of items to be discussed at a meeting","e":"Please review the agenda before the meeting starts.","s":["schedule","plan","itinerary"],"wf":[{"w":"agenda","p":"noun (no verb form)"}],"ety":"From Latin 'agenda' (things to be done), plural of 'agendum', from 'agere' (to do). Entered English in the 17th century."},
{"w":"amendment","pos":"noun","cat":"NOUN","m":"a formal change","tr":"amandemen / perubahan resmi","i":"a change or addition made to a document or law","e":"The board approved an amendment to the original contract.","s":["revision","modification","change"],"wf":[{"w":"amend","p":"verb"},{"w":"amended","p":"adj"}],"ety":"From Old French 'amendement', from 'amender' (to correct), from Latin 'emendare' (to free from fault). Entered English in the 13th century."},
{"w":"audit","pos":"noun","cat":"NOUN","m":"official financial check","tr":"audit / pemeriksaan keuangan","i":"an official examination of financial accounts","e":"The annual audit revealed no significant irregularities.","s":["inspection","review","examination"],"wf":[{"w":"audit","p":"verb"},{"w":"auditor","p":"noun"},{"w":"audited","p":"adj"}],"ety":"From Latin 'auditus' (a hearing), from 'audire' (to hear). Originally referred to an oral examination of accounts; entered English in the 15th century."},
{"w":"benchmark","pos":"noun","cat":"NOUN","m":"a standard for comparison","tr":"tolok ukur / patokan","i":"a standard or point of reference used for comparison","e":"The company uses industry benchmarks to measure its performance.","s":["standard","reference","criterion"],"wf":[{"w":"benchmark","p":"verb"},{"w":"benchmarking","p":"noun"}],"ety":"Originally a surveying term (19th century) for a mark cut in stone as a reference point. Applied to business standards in the 20th century."},
{"w":"budget","pos":"noun","cat":"NOUN","m":"financial plan","tr":"anggaran","i":"an estimate of income and expenditure for a set period","e":"The marketing budget for next year has been increased by 15 percent.","s":["allocation","funds","financial plan"],"wf":[{"w":"budget","p":"verb"},{"w":"budgetary","p":"adj"}],"ety":"From Old French 'bougette' (small bag), from 'bouge' (leather bag). The financial meaning developed in the 18th century when the British Chancellor presented the annual financial statement."},
{"w":"candidate","pos":"noun","cat":"NOUN","m":"a person applying for a job","tr":"kandidat / pelamar","i":"a person who applies for a job or is nominated for a position","e":"We received over 200 applications from qualified candidates.","s":["applicant","nominee","contender"],"wf":[{"w":"candidacy","p":"noun"},{"w":"candidature","p":"noun"}],"ety":"From Latin 'candidatus' (clothed in white), from 'candidus' (white). Roman candidates for office wore white togas; entered English in the 17th century."},
{"w":"capacity","pos":"noun","cat":"NOUN","m":"maximum amount possible","tr":"kapasitas","i":"the maximum amount that something can contain or produce","e":"The factory is currently operating at full capacity.","s":["volume","limit","output"],"wf":[{"w":"capable","p":"adj"},{"w":"capacitate","p":"verb"}],"ety":"From Latin 'capacitas' (ability to hold), from 'capax' (able to hold), from 'capere' (to take). Entered English in the 15th century."},
{"w":"certificate","pos":"noun","cat":"NOUN","m":"official document of achievement","tr":"sertifikat","i":"an official document proving a fact or qualification","e":"Participants will receive a certificate upon completion of the course.","s":["credential","diploma","document"],"wf":[{"w":"certify","p":"verb"},{"w":"certified","p":"adj"},{"w":"certification","p":"noun"}],"ety":"From Medieval Latin 'certificatum', from 'certificare' (to certify), from 'certus' (certain) + 'facere' (to make). Entered English in the 15th century."},
{"w":"compliance","pos":"noun","cat":"NOUN","m":"following rules","tr":"kepatuhan","i":"the act of obeying rules, regulations, or standards","e":"All employees must complete the annual compliance training.","s":["adherence","conformity","observance"],"wf":[{"w":"comply","p":"verb"},{"w":"compliant","p":"adj"}],"ety":"From Latin 'complere' (to fill up, fulfill). The noun 'compliance' entered English in the 17th century, originally meaning a disposition to yield."},
{"w":"contractor","pos":"noun","cat":"NOUN","m":"an independent worker","tr":"kontraktor","i":"a person or company hired to do specific work under a contract","e":"We hired an outside contractor to handle the renovation.","s":["subcontractor","freelancer","vendor"],"wf":[{"w":"contract","p":"noun/verb"},{"w":"contractual","p":"adj"}],"ety":"From Latin 'contractus' (drawn together), from 'contrahere' (to draw together). The sense of a hired worker developed in the 19th century."},
{"w":"deficit","pos":"noun","cat":"NOUN","m":"a shortfall in funds","tr":"defisit / kekurangan dana","i":"the amount by which something falls short of what is needed","e":"The company reported a budget deficit for the third quarter.","s":["shortfall","loss","gap"],"wf":[{"w":"deficient","p":"adj"},{"w":"deficiency","p":"noun"}],"ety":"From Latin 'deficit' (it is lacking), from 'deficere' (to fail), from 'de-' (away) + 'facere' (to do). Entered English in the 18th century."},
{"w":"endorsement","pos":"noun","cat":"NOUN","m":"official support or approval","tr":"dukungan resmi / pengesahan","i":"a public statement of support or approval","e":"The product received an endorsement from a well-known athlete.","s":["approval","backing","support"],"wf":[{"w":"endorse","p":"verb"},{"w":"endorsed","p":"adj"}],"ety":"From Old French 'endosser' (to put on the back), from 'en-' (on) + 'dos' (back). Originally meant signing the back of a document; the approval sense developed later."},
{"w":"expenditure","pos":"noun","cat":"NOUN","m":"money spent","tr":"pengeluaran","i":"the total amount of money spent","e":"The company needs to reduce its expenditure on travel.","s":["spending","expense","outlay"],"wf":[{"w":"expend","p":"verb"},{"w":"expendable","p":"adj"}],"ety":"From Medieval Latin 'expenditura', from 'expendere' (to weigh out, pay), from 'ex-' (out) + 'pendere' (to weigh). Entered English in the 18th century."},
{"w":"forecast","pos":"noun","cat":"NOUN","m":"a prediction of future events","tr":"perkiraan / prakiraan","i":"a statement about what is likely to happen in the future","e":"The sales forecast for next year looks very promising.","s":["prediction","projection","estimate"],"wf":[{"w":"forecast","p":"verb"},{"w":"forecaster","p":"noun"}],"ety":"Compound of 'fore-' (before) + 'cast' (to throw, calculate). Originally a nautical term; the business sense of predicting future conditions developed in the 19th century."},
{"w":"franchise","pos":"noun","cat":"NOUN","m":"a licensed business model","tr":"waralaba","i":"a license to operate a business using another company brand","e":"She opened a franchise of the popular coffee chain.","s":["license","branch","outlet"],"wf":[{"w":"franchise","p":"verb"},{"w":"franchisee","p":"noun"},{"w":"franchisor","p":"noun"}],"ety":"From Old French 'franchise' (freedom), from 'franc' (free). Originally meant a legal privilege; the business licensing sense developed in the 20th century."},
{"w":"headquarters","pos":"noun","cat":"NOUN","m":"main office location","tr":"kantor pusat","i":"the main office or center of operations of an organization","e":"The company headquarters is located in downtown Chicago.","s":["head office","main office","base"],"wf":[{"w":"headquarter","p":"verb (rare)"}],"ety":"Military term from the 17th century, referring to the place where the commanding officer was stationed. Applied to business organizations in the 19th century."},
{"w":"incentive","pos":"noun","cat":"NOUN","m":"a reward to motivate action","tr":"insentif / motivasi","i":"something that motivates or encourages someone to do something","e":"The company offers financial incentives for meeting sales targets.","s":["reward","motivation","bonus"],"wf":[{"w":"incentivize","p":"verb"},{"w":"incentivized","p":"adj"}],"ety":"From Latin 'incentivum' (that which sets the tune), from 'incentivus' (setting the tune), from 'incinere' (to sing). Entered English in the 15th century."},
{"w":"inventory","pos":"noun","cat":"NOUN","m":"a list of stock","tr":"inventaris / stok barang","i":"a complete list of items in stock","e":"The warehouse team conducts a full inventory check every quarter.","s":["stock","supply","stockpile"],"wf":[{"w":"inventory","p":"verb"},{"w":"inventoried","p":"adj"}],"ety":"From Medieval Latin 'inventarium' (a list of what is found), from 'invenire' (to find). Entered English in the 15th century."},
{"w":"invoice","pos":"noun","cat":"NOUN","m":"a bill for goods or services","tr":"faktur / tagihan","i":"a document requesting payment for goods or services provided","e":"Please send the invoice to the accounts payable department.","s":["bill","statement","receipt"],"wf":[{"w":"invoice","p":"verb"},{"w":"invoiced","p":"adj"}],"ety":"From French 'envois' (dispatches), plural of 'envoi' (a sending), from 'envoyer' (to send). Entered English in the 16th century."},
{"w":"liability","pos":"noun","cat":"NOUN","m":"legal responsibility","tr":"kewajiban hukum / tanggung jawab","i":"the state of being legally responsible for something","e":"The company accepted liability for the defective products.","s":["responsibility","obligation","accountability"],"wf":[{"w":"liable","p":"adj"},{"w":"liabilities","p":"noun (plural)"}],"ety":"From French 'liable', from 'lier' (to bind), from Latin 'ligare' (to bind). The legal sense entered English in the 18th century."},
{"w":"merger","pos":"noun","cat":"NOUN","m":"combining two companies","tr":"merger / penggabungan perusahaan","i":"the combining of two companies into one","e":"The merger between the two firms was completed last month.","s":["acquisition","consolidation","union"],"wf":[{"w":"merge","p":"verb"},{"w":"merged","p":"adj"}],"ety":"From Anglo-French 'merger' (to dip, plunge), from Latin 'mergere' (to dip). The legal/business sense of combining entities developed in the 19th century."},
{"w":"momentum","pos":"noun","cat":"NOUN","m":"forward progress","tr":"momentum / dorongan maju","i":"the force or speed of movement; growing strength","e":"The project gained momentum after the initial funding was secured.","s":["progress","drive","impetus"],"wf":[{"w":"momentous","p":"adj"},{"w":"momentarily","p":"adv"}],"ety":"From Latin 'momentum' (movement, moment), from 'movere' (to move). Originally a physics term; the figurative business sense developed in the 19th century."},
{"w":"obligation","pos":"noun","cat":"NOUN","m":"a duty or requirement","tr":"kewajiban","i":"something you are required to do by law or morally","e":"It is your obligation to report any safety hazards immediately.","s":["duty","responsibility","requirement"],"wf":[{"w":"oblige","p":"verb"},{"w":"obligatory","p":"adj"},{"w":"obliged","p":"adj"}],"ety":"From Latin 'obligatio' (a binding), from 'obligare' (to bind), from 'ob-' (to) + 'ligare' (to bind). Entered English in the 14th century."},
{"w":"overhead","pos":"noun","cat":"NOUN","m":"ongoing business costs","tr":"biaya operasional tetap","i":"the regular costs of running a business, not including production","e":"Reducing overhead is essential to improving profit margins.","s":["expenses","running costs","operating costs"],"wf":[{"w":"overhead","p":"adj/adv"}],"ety":"Originally referred to costs that could not be attributed to a specific product. The business accounting sense developed in the 19th century."},
{"w":"patent","pos":"noun","cat":"NOUN","m":"exclusive rights to an invention","tr":"paten","i":"a government license giving exclusive rights to an invention","e":"The company filed a patent for its new manufacturing process.","s":["license","copyright","intellectual property"],"wf":[{"w":"patent","p":"verb"},{"w":"patented","p":"adj"},{"w":"patentable","p":"adj"}],"ety":"From Latin 'patens' (open, lying open), from 'patere' (to be open). 'Letters patent' were open royal documents granting rights; entered English in the 14th century."},
{"w":"procurement","pos":"noun","cat":"NOUN","m":"obtaining goods or services","tr":"pengadaan barang / jasa","i":"the process of obtaining goods or services for a business","e":"The procurement team is responsible for sourcing all office supplies.","s":["purchasing","acquisition","sourcing"],"wf":[{"w":"procure","p":"verb"},{"w":"procurer","p":"noun"}],"ety":"From Old French 'procurement', from 'procurer' (to take care of), from Latin 'procurare' (to manage). Entered English in the 15th century."},
{"w":"productivity","pos":"noun","cat":"NOUN","m":"efficiency of output","tr":"produktivitas","i":"the effectiveness of productive effort","e":"The new software significantly improved team productivity.","s":["efficiency","output","performance"],"wf":[{"w":"produce","p":"verb"},{"w":"productive","p":"adj"},{"w":"productively","p":"adv"}],"ety":"From Medieval Latin 'productivus' (capable of producing), from 'producere' (to lead forward). The economic sense of output per unit of input developed in the 19th century."},
{"w":"proposal","pos":"noun","cat":"NOUN","m":"a formal suggestion","tr":"proposal / usulan resmi","i":"a plan or suggestion put forward for consideration","e":"The client approved our proposal for the new website design.","s":["suggestion","plan","offer"],"wf":[{"w":"propose","p":"verb"},{"w":"proposed","p":"adj"}],"ety":"From Medieval Latin 'proposale', from 'proponere' (to put forward). Entered English in the 17th century."},
{"w":"quota","pos":"noun","cat":"NOUN","m":"a fixed target amount","tr":"kuota / target tetap","i":"a fixed share or target that must be achieved","e":"Each sales representative has a monthly quota to meet.","s":["target","limit","allocation"],"wf":[{"w":"quota","p":"noun (no common verb)"}],"ety":"From Medieval Latin 'quota pars' (how large a part), from 'quotus' (of what number). Entered English in the 17th century."},
{"w":"revenue","pos":"noun","cat":"NOUN","m":"income from business","tr":"pendapatan / pemasukan","i":"the income generated from normal business operations","e":"The company reported record revenue in the fourth quarter.","s":["income","earnings","turnover"],"wf":[{"w":"revenue","p":"noun (no common verb)"}],"ety":"From Old French 'revenue' (return), from 'revenir' (to return), from Latin 'revenire'. Originally meant income from land; the general business sense developed later."},
{"w":"subsidiary","pos":"noun","cat":"NOUN","m":"a company owned by another","tr":"anak perusahaan","i":"a company controlled by a larger parent company","e":"The firm opened a new subsidiary in Southeast Asia.","s":["branch","affiliate","division"],"wf":[{"w":"subsidize","p":"verb"},{"w":"subsidy","p":"noun"},{"w":"subsidiary","p":"adj"}],"ety":"From Latin 'subsidiarius' (of the reserve troops), from 'subsidium' (reserve troops, support). The business sense of a dependent company developed in the 19th century."},
{"w":"surplus","pos":"noun","cat":"NOUN","m":"an excess amount","tr":"surplus / kelebihan","i":"an amount left over when requirements have been met","e":"The department ended the year with a budget surplus.","s":["excess","remainder","leftover"],"wf":[{"w":"surplus","p":"adj"}],"ety":"From Old French 'surplus' (over and above), from Medieval Latin 'superplus', from 'super-' (over) + 'plus' (more). Entered English in the 14th century."},
{"w":"turnover","pos":"noun","cat":"NOUN","m":"total sales or staff changes","tr":"omzet / pergantian karyawan","i":"the amount of business done, or the rate at which staff leave","e":"High staff turnover is a sign of low employee satisfaction.","s":["revenue","sales","attrition"],"wf":[{"w":"turn over","p":"verb phrase"}],"ety":"Compound of 'turn' + 'over'. The financial sense (total sales) and the HR sense (rate of staff replacement) both developed in the 20th century."},
{"w":"vendor","pos":"noun","cat":"NOUN","m":"a supplier or seller","tr":"vendor / pemasok","i":"a person or company that sells goods or services","e":"We are evaluating three vendors for the new office furniture contract.","s":["supplier","seller","provider"],"wf":[{"w":"vend","p":"verb"},{"w":"vending","p":"adj/noun"}],"ety":"From Latin 'vendere' (to sell), from 'venum dare' (to give for sale). Entered English in the 17th century."},
{"w":"warranty","pos":"noun","cat":"NOUN","m":"a guarantee on a product","tr":"garansi","i":"a written guarantee promising to repair or replace a product","e":"The appliance comes with a two-year warranty.","s":["guarantee","assurance","coverage"],"wf":[{"w":"warrant","p":"verb/noun"},{"w":"warranted","p":"adj"}],"ety":"From Old French 'warantie' (guarantee), from 'warantir' (to guarantee), from 'warant' (protector). Entered English in the 15th century."},
{"w":"workforce","pos":"noun","cat":"NOUN","m":"all employees of a company","tr":"tenaga kerja / angkatan kerja","i":"the people engaged in or available for work","e":"The company plans to expand its workforce by 20 percent next year.","s":["staff","employees","personnel"],"wf":[{"w":"work","p":"verb/noun"},{"w":"worker","p":"noun"}],"ety":"Compound of 'work' + 'force'. Emerged in American English in the early 20th century to describe the total labor pool available to an organization."},
]

with open("public/games/flashcard_lengkap_intact/toeic_test06_vocab.html", "a", encoding="utf-8") as f:
    for w in nouns:
        f.write("  " + json.dumps(w, ensure_ascii=False) + ",\n")

print(f"Written {len(nouns)} nouns")
