import json

nouns = [
{"w":"agenda","pos":"noun","cat":"NOUN","m":"list of meeting topics","tr":"agenda / daftar topik rapat","i":"a list of items to be discussed at a meeting","e":"Please review the agenda before the meeting starts.","s":["schedule","plan","itinerary"],"wf":[{"w":"agenda","p":"noun (tidak ada bentuk kata kerja)"}],"ety":"Dari bahasa Latin 'agenda' (hal-hal yang harus dilakukan), bentuk jamak dari 'agendum', dari 'agere' (melakukan). Masuk ke bahasa Inggris pada abad ke-17.","q":"The ___ for today's meeting includes budget review and project updates."},
{"w":"amendment","pos":"noun","cat":"NOUN","m":"a formal change","tr":"amandemen / perubahan resmi","i":"a change or addition made to a document or law","e":"The board approved an amendment to the original contract.","s":["revision","modification","change"],"wf":[{"w":"amend","p":"verb"},{"w":"amended","p":"adj"}],"ety":"Dari bahasa Prancis Kuno 'amendement', dari 'amender' (memperbaiki), dari bahasa Latin 'emendare' (membebaskan dari kesalahan). Masuk ke bahasa Inggris pada abad ke-13.","q":"The committee proposed an ___ to the existing employment policy."},
{"w":"audit","pos":"noun","cat":"NOUN","m":"official financial check","tr":"audit / pemeriksaan keuangan","i":"an official examination of financial accounts","e":"The annual audit revealed no significant irregularities.","s":["inspection","review","examination"],"wf":[{"w":"audit","p":"verb"},{"w":"auditor","p":"noun"},{"w":"audited","p":"adj"}],"ety":"Dari bahasa Latin 'auditus' (pendengaran), dari 'audire' (mendengar). Awalnya merujuk pada pemeriksaan akun secara lisan; masuk ke bahasa Inggris pada abad ke-15.","q":"The external ___ found several discrepancies in the company's financial records."},
{"w":"benchmark","pos":"noun","cat":"NOUN","m":"a standard for comparison","tr":"tolok ukur / patokan","i":"a standard or point of reference used for comparison","e":"The company uses industry benchmarks to measure its performance.","s":["standard","reference","criterion"],"wf":[{"w":"benchmark","p":"verb"},{"w":"benchmarking","p":"noun"}],"ety":"Awalnya istilah survei (abad ke-19) untuk tanda yang diukir di batu sebagai titik referensi. Diterapkan pada standar bisnis pada abad ke-20.","q":"The company set a new ___ for customer service response time in the industry."},
{"w":"budget","pos":"noun","cat":"NOUN","m":"financial plan","tr":"anggaran","i":"an estimate of income and expenditure for a set period","e":"The marketing budget for next year has been increased by 15 percent.","s":["allocation","funds","financial plan"],"wf":[{"w":"budget","p":"verb"},{"w":"budgetary","p":"adj"}],"ety":"Dari bahasa Prancis Kuno 'bougette' (tas kecil), dari 'bouge' (tas kulit). Makna keuangan berkembang pada abad ke-18 ketika Menteri Keuangan Inggris mempresentasikan laporan keuangan tahunan.","q":"The department exceeded its ___ by 20 percent due to unexpected expenses."},
{"w":"candidate","pos":"noun","cat":"NOUN","m":"a person applying for a job","tr":"kandidat / pelamar","i":"a person who applies for a job or is nominated for a position","e":"We received over 200 applications from qualified candidates.","s":["applicant","nominee","contender"],"wf":[{"w":"candidacy","p":"noun"},{"w":"candidature","p":"noun"}],"ety":"Dari bahasa Latin 'candidatus' (berpakaian putih), dari 'candidus' (putih). Calon pejabat Romawi mengenakan toga putih; masuk ke bahasa Inggris pada abad ke-17.","q":"The HR team shortlisted five ___ for the senior manager position."},
{"w":"capacity","pos":"noun","cat":"NOUN","m":"maximum amount possible","tr":"kapasitas","i":"the maximum amount that something can contain or produce","e":"The factory is currently operating at full capacity.","s":["volume","limit","output"],"wf":[{"w":"capable","p":"adj"},{"w":"capacitate","p":"verb"}],"ety":"Dari bahasa Latin 'capacitas' (kemampuan menampung), dari 'capax' (mampu menampung), dari 'capere' (mengambil). Masuk ke bahasa Inggris pada abad ke-15.","q":"The new warehouse has a storage ___ of 10,000 units."},
{"w":"certificate","pos":"noun","cat":"NOUN","m":"official document of achievement","tr":"sertifikat","i":"an official document proving a fact or qualification","e":"Participants will receive a certificate upon completion of the course.","s":["credential","diploma","document"],"wf":[{"w":"certify","p":"verb"},{"w":"certified","p":"adj"},{"w":"certification","p":"noun"}],"ety":"Dari bahasa Latin Abad Pertengahan 'certificatum', dari 'certificare' (mensertifikasi), dari 'certus' (pasti) + 'facere' (membuat). Masuk ke bahasa Inggris pada abad ke-15.","q":"All participants who complete the training will receive a ___ of completion."},
{"w":"compliance","pos":"noun","cat":"NOUN","m":"following rules","tr":"kepatuhan","i":"the act of obeying rules, regulations, or standards","e":"All employees must complete the annual compliance training.","s":["adherence","conformity","observance"],"wf":[{"w":"comply","p":"verb"},{"w":"compliant","p":"adj"}],"ety":"Dari bahasa Latin 'complere' (mengisi penuh, memenuhi). Kata benda 'compliance' masuk ke bahasa Inggris pada abad ke-17, awalnya berarti kecenderungan untuk mengalah.","q":"The company must ensure full ___ with all environmental regulations."},
{"w":"contractor","pos":"noun","cat":"NOUN","m":"an independent worker","tr":"kontraktor","i":"a person or company hired to do specific work under a contract","e":"We hired an outside contractor to handle the renovation.","s":["subcontractor","freelancer","vendor"],"wf":[{"w":"contract","p":"noun/verb"},{"w":"contractual","p":"adj"}],"ety":"Dari bahasa Latin 'contractus' (ditarik bersama), dari 'contrahere' (menarik bersama). Makna pekerja yang disewa berkembang pada abad ke-19.","q":"The company hired an independent ___ to install the new security system."},
{"w":"deficit","pos":"noun","cat":"NOUN","m":"a shortfall in funds","tr":"defisit / kekurangan dana","i":"the amount by which something falls short of what is needed","e":"The company reported a budget deficit for the third quarter.","s":["shortfall","loss","gap"],"wf":[{"w":"deficient","p":"adj"},{"w":"deficiency","p":"noun"}],"ety":"Dari bahasa Latin 'deficit' (kurang), dari 'deficere' (gagal), dari 'de-' (jauh) + 'facere' (melakukan). Masuk ke bahasa Inggris pada abad ke-18.","q":"The government announced a trade ___ of $2 billion for the last quarter."},
{"w":"endorsement","pos":"noun","cat":"NOUN","m":"official support or approval","tr":"dukungan resmi / pengesahan","i":"a public statement of support or approval","e":"The product received an endorsement from a well-known athlete.","s":["approval","backing","support"],"wf":[{"w":"endorse","p":"verb"},{"w":"endorsed","p":"adj"}],"ety":"Dari bahasa Prancis Kuno 'endosser' (menaruh di punggung), dari 'en-' (di) + 'dos' (punggung). Awalnya berarti menandatangani bagian belakang dokumen; makna persetujuan berkembang kemudian.","q":"The charity received a public ___ from several well-known celebrities."},
{"w":"expenditure","pos":"noun","cat":"NOUN","m":"money spent","tr":"pengeluaran","i":"the total amount of money spent","e":"The company needs to reduce its expenditure on travel.","s":["spending","expense","outlay"],"wf":[{"w":"expend","p":"verb"},{"w":"expendable","p":"adj"}],"ety":"Dari bahasa Latin Abad Pertengahan 'expenditura', dari 'expendere' (menimbang, membayar), dari 'ex-' (keluar) + 'pendere' (menimbang). Masuk ke bahasa Inggris pada abad ke-18.","q":"The board voted to reduce annual ___ on non-essential services by 10 percent."},
{"w":"forecast","pos":"noun","cat":"NOUN","m":"a prediction of future events","tr":"perkiraan / prakiraan","i":"a statement about what is likely to happen in the future","e":"The sales forecast for next year looks very promising.","s":["prediction","projection","estimate"],"wf":[{"w":"forecast","p":"verb"},{"w":"forecaster","p":"noun"}],"ety":"Gabungan kata 'fore-' (sebelum) + 'cast' (melempar, menghitung). Awalnya istilah pelayaran; makna bisnis untuk memprediksi kondisi masa depan berkembang pada abad ke-19.","q":"According to the financial ___, revenue is expected to grow by 12 percent next year."},
{"w":"franchise","pos":"noun","cat":"NOUN","m":"a licensed business model","tr":"waralaba","i":"a license to operate a business using another company brand","e":"She opened a franchise of the popular coffee chain.","s":["license","branch","outlet"],"wf":[{"w":"franchise","p":"verb"},{"w":"franchisee","p":"noun"},{"w":"franchisor","p":"noun"}],"ety":"Dari bahasa Prancis Kuno 'franchise' (kebebasan), dari 'franc' (bebas). Awalnya berarti hak istimewa hukum; makna lisensi bisnis berkembang pada abad ke-20.","q":"The entrepreneur invested in a fast-food ___ and opened three locations."},
{"w":"headquarters","pos":"noun","cat":"NOUN","m":"main office location","tr":"kantor pusat","i":"the main office or center of operations of an organization","e":"The company headquarters is located in downtown Chicago.","s":["head office","main office","base"],"wf":[{"w":"headquarter","p":"verb (jarang)"}],"ety":"Istilah militer dari abad ke-17, merujuk pada tempat komandan ditempatkan. Diterapkan pada organisasi bisnis pada abad ke-19.","q":"The company's ___ will be relocated from New York to Austin next year."},
{"w":"incentive","pos":"noun","cat":"NOUN","m":"a reward to motivate action","tr":"insentif / motivasi","i":"something that motivates or encourages someone to do something","e":"The company offers financial incentives for meeting sales targets.","s":["reward","motivation","bonus"],"wf":[{"w":"incentivize","p":"verb"},{"w":"incentivized","p":"adj"}],"ety":"Dari bahasa Latin 'incentivum' (yang mengatur nada), dari 'incentivus' (mengatur nada), dari 'incinere' (bernyanyi). Masuk ke bahasa Inggris pada abad ke-15.","q":"The company introduced a performance ___ to motivate the sales team."},
{"w":"inventory","pos":"noun","cat":"NOUN","m":"a list of stock","tr":"inventaris / stok barang","i":"a complete list of items in stock","e":"The warehouse team conducts a full inventory check every quarter.","s":["stock","supply","stockpile"],"wf":[{"w":"inventory","p":"verb"},{"w":"inventoried","p":"adj"}],"ety":"Dari bahasa Latin Abad Pertengahan 'inventarium' (daftar apa yang ditemukan), dari 'invenire' (menemukan). Masuk ke bahasa Inggris pada abad ke-15.","q":"The store manager discovered a shortage during the monthly ___ check."},
{"w":"invoice","pos":"noun","cat":"NOUN","m":"a bill for goods or services","tr":"faktur / tagihan","i":"a document requesting payment for goods or services provided","e":"Please send the invoice to the accounts payable department.","s":["bill","statement","receipt"],"wf":[{"w":"invoice","p":"verb"},{"w":"invoiced","p":"adj"}],"ety":"Dari bahasa Prancis 'envois' (pengiriman), bentuk jamak dari 'envoi' (pengiriman), dari 'envoyer' (mengirim). Masuk ke bahasa Inggris pada abad ke-16.","q":"Please send the ___ to our accounting department within 30 days of delivery."},
{"w":"liability","pos":"noun","cat":"NOUN","m":"legal responsibility","tr":"kewajiban hukum / tanggung jawab","i":"the state of being legally responsible for something","e":"The company accepted liability for the defective products.","s":["responsibility","obligation","accountability"],"wf":[{"w":"liable","p":"adj"},{"w":"liabilities","p":"noun (jamak)"}],"ety":"Dari bahasa Prancis 'liable', dari 'lier' (mengikat), dari bahasa Latin 'ligare' (mengikat). Makna hukum masuk ke bahasa Inggris pada abad ke-18.","q":"The company's total ___ increased significantly after the lawsuit was filed."},
{"w":"merger","pos":"noun","cat":"NOUN","m":"combining two companies","tr":"merger / penggabungan perusahaan","i":"the combining of two companies into one","e":"The merger between the two firms was completed last month.","s":["acquisition","consolidation","union"],"wf":[{"w":"merge","p":"verb"},{"w":"merged","p":"adj"}],"ety":"Dari bahasa Prancis Anglo 'merger' (mencelupkan), dari bahasa Latin 'mergere' (mencelupkan). Makna hukum/bisnis menggabungkan entitas berkembang pada abad ke-19.","q":"The ___ between the two airlines created the largest carrier in the region."},
{"w":"momentum","pos":"noun","cat":"NOUN","m":"forward progress","tr":"momentum / dorongan maju","i":"the force or speed of movement; growing strength","e":"The project gained momentum after the initial funding was secured.","s":["progress","drive","impetus"],"wf":[{"w":"momentous","p":"adj"},{"w":"momentarily","p":"adv"}],"ety":"Dari bahasa Latin 'momentum' (gerakan, momen), dari 'movere' (bergerak). Awalnya istilah fisika; makna kiasan bisnis berkembang pada abad ke-19.","q":"The startup gained ___ after its product was featured in a major magazine."},
{"w":"obligation","pos":"noun","cat":"NOUN","m":"a duty or requirement","tr":"kewajiban","i":"something you are required to do by law or morally","e":"It is your obligation to report any safety hazards immediately.","s":["duty","responsibility","requirement"],"wf":[{"w":"oblige","p":"verb"},{"w":"obligatory","p":"adj"},{"w":"obliged","p":"adj"}],"ety":"Dari bahasa Latin 'obligatio' (pengikatan), dari 'obligare' (mengikat), dari 'ob-' (ke) + 'ligare' (mengikat). Masuk ke bahasa Inggris pada abad ke-14.","q":"It is the employer's ___ to provide a safe working environment for all staff."},
{"w":"overhead","pos":"noun","cat":"NOUN","m":"ongoing business costs","tr":"biaya operasional tetap","i":"the regular costs of running a business, not including production","e":"Reducing overhead is essential to improving profit margins.","s":["expenses","running costs","operating costs"],"wf":[{"w":"overhead","p":"adj/adv"}],"ety":"Awalnya merujuk pada biaya yang tidak dapat dikaitkan dengan produk tertentu. Makna akuntansi bisnis berkembang pada abad ke-19.","q":"The company reduced its ___ by moving to a smaller office space."},
{"w":"patent","pos":"noun","cat":"NOUN","m":"exclusive rights to an invention","tr":"paten","i":"a government license giving exclusive rights to an invention","e":"The company filed a patent for its new manufacturing process.","s":["license","copyright","intellectual property"],"wf":[{"w":"patent","p":"verb"},{"w":"patented","p":"adj"},{"w":"patentable","p":"adj"}],"ety":"Dari bahasa Latin 'patens' (terbuka), dari 'patere' (terbuka). 'Surat paten' adalah dokumen kerajaan terbuka yang memberikan hak; masuk ke bahasa Inggris pada abad ke-14.","q":"The inventor filed a ___ to protect her new design from being copied."},
{"w":"procurement","pos":"noun","cat":"NOUN","m":"obtaining goods or services","tr":"pengadaan barang / jasa","i":"the process of obtaining goods or services for a business","e":"The procurement team is responsible for sourcing all office supplies.","s":["purchasing","acquisition","sourcing"],"wf":[{"w":"procure","p":"verb"},{"w":"procurer","p":"noun"}],"ety":"Dari bahasa Prancis Kuno 'procurement', dari 'procurer' (mengurus), dari bahasa Latin 'procurare' (mengelola). Masuk ke bahasa Inggris pada abad ke-15.","q":"The ___ department is responsible for negotiating contracts with all suppliers."},
{"w":"productivity","pos":"noun","cat":"NOUN","m":"efficiency of output","tr":"produktivitas","i":"the effectiveness of productive effort","e":"The new software significantly improved team productivity.","s":["efficiency","output","performance"],"wf":[{"w":"produce","p":"verb"},{"w":"productive","p":"adj"},{"w":"productively","p":"adv"}],"ety":"Dari bahasa Latin Abad Pertengahan 'productivus' (mampu menghasilkan), dari 'producere' (memimpin ke depan). Makna ekonomi output per unit input berkembang pada abad ke-19.","q":"Working from home has increased employee ___ by reducing commute time."},
{"w":"proposal","pos":"noun","cat":"NOUN","m":"a formal suggestion","tr":"proposal / usulan resmi","i":"a plan or suggestion put forward for consideration","e":"The client approved our proposal for the new website design.","s":["suggestion","plan","offer"],"wf":[{"w":"propose","p":"verb"},{"w":"proposed","p":"adj"}],"ety":"Dari bahasa Latin Abad Pertengahan 'proposale', dari 'proponere' (mengajukan). Masuk ke bahasa Inggris pada abad ke-17.","q":"The team submitted a detailed ___ for the new office renovation project."},
{"w":"quota","pos":"noun","cat":"NOUN","m":"a fixed target amount","tr":"kuota / target tetap","i":"a fixed share or target that must be achieved","e":"Each sales representative has a monthly quota to meet.","s":["target","limit","allocation"],"wf":[{"w":"quota","p":"noun (tidak ada bentuk kata kerja umum)"}],"ety":"Dari bahasa Latin Abad Pertengahan 'quota pars' (berapa besar bagiannya), dari 'quotus' (dari nomor berapa). Masuk ke bahasa Inggris pada abad ke-17.","q":"The sales team exceeded their monthly ___ by 30 percent this quarter."},
{"w":"revenue","pos":"noun","cat":"NOUN","m":"income from business","tr":"pendapatan / pemasukan","i":"the income generated from normal business operations","e":"The company reported record revenue in the fourth quarter.","s":["income","earnings","turnover"],"wf":[{"w":"revenue","p":"noun (tidak ada bentuk kata kerja umum)"}],"ety":"Dari bahasa Prancis Kuno 'revenue' (kembali), dari 'revenir' (kembali), dari bahasa Latin 'revenire'. Awalnya berarti pendapatan dari tanah; makna bisnis umum berkembang kemudian.","q":"The company's annual ___ grew by 25 percent following the product launch."},
{"w":"subsidiary","pos":"noun","cat":"NOUN","m":"a company owned by another","tr":"anak perusahaan","i":"a company controlled by a larger parent company","e":"The firm opened a new subsidiary in Southeast Asia.","s":["branch","affiliate","division"],"wf":[{"w":"subsidize","p":"verb"},{"w":"subsidy","p":"noun"},{"w":"subsidiary","p":"adj"}],"ety":"Dari bahasa Latin 'subsidiarius' (dari pasukan cadangan), dari 'subsidium' (pasukan cadangan, dukungan). Makna bisnis perusahaan dependen berkembang pada abad ke-19.","q":"The parent company established a ___ in Singapore to expand into Asian markets."},
{"w":"surplus","pos":"noun","cat":"NOUN","m":"an excess amount","tr":"surplus / kelebihan","i":"an amount left over when requirements have been met","e":"The department ended the year with a budget surplus.","s":["excess","remainder","leftover"],"wf":[{"w":"surplus","p":"adj"}],"ety":"Dari bahasa Prancis Kuno 'surplus' (lebih dari yang diperlukan), dari bahasa Latin Abad Pertengahan 'superplus', dari 'super-' (di atas) + 'plus' (lebih). Masuk ke bahasa Inggris pada abad ke-14.","q":"The company donated its food ___ to local charities at the end of the year."},
{"w":"turnover","pos":"noun","cat":"NOUN","m":"total sales or staff changes","tr":"omzet / pergantian karyawan","i":"the amount of business done, or the rate at which staff leave","e":"High staff turnover is a sign of low employee satisfaction.","s":["revenue","sales","attrition"],"wf":[{"w":"turn over","p":"frasa kata kerja"}],"ety":"Gabungan kata 'turn' + 'over'. Makna keuangan (total penjualan) dan makna SDM (tingkat pergantian staf) keduanya berkembang pada abad ke-20.","q":"The company's annual ___ reached $50 million for the first time last year."},
{"w":"vendor","pos":"noun","cat":"NOUN","m":"a supplier or seller","tr":"vendor / pemasok","i":"a person or company that sells goods or services","e":"We are evaluating three vendors for the new office furniture contract.","s":["supplier","seller","provider"],"wf":[{"w":"vend","p":"verb"},{"w":"vending","p":"adj/noun"}],"ety":"Dari bahasa Latin 'vendere' (menjual), dari 'venum dare' (memberikan untuk dijual). Masuk ke bahasa Inggris pada abad ke-17.","q":"The company selected a new ___ to supply all its printing and stationery needs."},
{"w":"warranty","pos":"noun","cat":"NOUN","m":"a guarantee on a product","tr":"garansi","i":"a written guarantee promising to repair or replace a product","e":"The appliance comes with a two-year warranty.","s":["guarantee","assurance","coverage"],"wf":[{"w":"warrant","p":"verb/noun"},{"w":"warranted","p":"adj"}],"ety":"Dari bahasa Prancis Kuno 'warantie' (jaminan), dari 'warantir' (menjamin), dari 'warant' (pelindung). Masuk ke bahasa Inggris pada abad ke-15.","q":"The laptop comes with a one-year ___ that covers all manufacturing defects."},
{"w":"workforce","pos":"noun","cat":"NOUN","m":"all employees of a company","tr":"tenaga kerja / angkatan kerja","i":"the people engaged in or available for work","e":"The company plans to expand its workforce by 20 percent next year.","s":["staff","employees","personnel"],"wf":[{"w":"work","p":"verb/noun"},{"w":"worker","p":"noun"}],"ety":"Gabungan kata 'work' + 'force'. Muncul dalam bahasa Inggris Amerika pada awal abad ke-20 untuk menggambarkan total tenaga kerja yang tersedia bagi suatu organisasi.","q":"The company plans to increase its ___ by hiring 500 new employees this year."},
]

with open("public/games/flashcard_lengkap_intact/toeic_test06_vocab.html", "a", encoding="utf-8") as f:
    for w in nouns:
        f.write("  " + json.dumps(w, ensure_ascii=False) + ",\n")
print(f"Written {len(nouns)} nouns")
