import json

words = [
# ── VERBS ──
{"w":"authorize","pos":"verb","cat":"VERB","m":"to officially approve","tr":"mengizinkan secara resmi","i":"to give official permission for something","e":"Only the manager is authorized to approve expense reports.","s":["approve","permit","sanction"],"wf":[{"w":"authorization","p":"noun"},{"w":"authorized","p":"adj"},{"w":"authority","p":"noun"}],"ety":"Dari bahasa Latin 'auctorizare' (memberi wewenang), dari kata 'auctor' (pencetus). Masuk ke bahasa Inggris melalui bahasa Prancis Kuno pada abad ke-14.","q":"Only the director is ___ to sign financial documents."},
{"w":"consolidate","pos":"verb","cat":"VERB","m":"to combine into one","tr":"menggabungkan menjadi satu","i":"to merge separate things into a single stronger unit","e":"The company plans to consolidate its two offices into one location.","s":["merge","combine","unify"],"wf":[{"w":"consolidation","p":"noun"},{"w":"consolidated","p":"adj"}],"ety":"Dari bahasa Latin 'consolidare' (membuat padat), dari 'con-' (bersama) + 'solidus' (padat). Digunakan dalam bahasa Inggris sejak abad ke-16.","q":"The firm decided to ___ its three regional branches into one headquarters."},
{"w":"retain","pos":"verb","cat":"VERB","m":"to keep or maintain","tr":"mempertahankan","i":"to continue to have something; not to lose it","e":"The company has managed to retain its top employees for over a decade.","s":["keep","maintain","preserve"],"wf":[{"w":"retention","p":"noun"},{"w":"retentive","p":"adj"}],"ety":"Dari bahasa Latin 'retinere' (menahan kembali), dari 're-' (kembali) + 'tenere' (memegang). Masuk ke bahasa Inggris pada abad ke-15.","q":"The company offered higher salaries to ___ its best engineers."},
{"w":"revise","pos":"verb","cat":"VERB","m":"to update or correct","tr":"merevisi / memperbaiki","i":"to make changes to improve or correct something","e":"Please revise the proposal before submitting it to the client.","s":["update","amend","edit"],"wf":[{"w":"revision","p":"noun"},{"w":"revised","p":"adj"}],"ety":"Dari bahasa Latin 'revisere' (melihat kembali), dari 're-' (lagi) + 'videre' (melihat). Masuk ke bahasa Inggris pada abad ke-17.","q":"The editor asked the writer to ___ the draft before publication."},
{"w":"notify","pos":"verb","cat":"VERB","m":"to inform officially","tr":"memberitahukan secara resmi","i":"to formally tell someone about something","e":"Please notify the HR department of any changes to your personal information.","s":["inform","alert","advise"],"wf":[{"w":"notification","p":"noun"},{"w":"notice","p":"noun"}],"ety":"Dari bahasa Latin 'notificare' (membuat diketahui), dari 'notus' (diketahui) + 'facere' (membuat). Digunakan dalam bahasa Inggris sejak abad ke-15.","q":"Please ___ us immediately if you are unable to attend the meeting."},
{"w":"finalize","pos":"verb","cat":"VERB","m":"to complete the last details","tr":"menyelesaikan tahap akhir","i":"to put the finishing touches on something","e":"We need to finalize the contract before the end of the week.","s":["complete","conclude","settle"],"wf":[{"w":"final","p":"adj"},{"w":"finalization","p":"noun"},{"w":"finally","p":"adv"}],"ety":"Dari bahasa Latin 'finalis' (tentang akhir), dari 'finis' (akhir). Bentuk kata kerja menjadi umum dalam bahasa Inggris Amerika pada abad ke-20.","q":"We need to ___ the budget report before the board meeting tomorrow."},
{"w":"outsource","pos":"verb","cat":"VERB","m":"to hire externally","tr":"mengalihdayakan","i":"to arrange for work to be done by an outside company","e":"The firm decided to outsource its IT support to a specialist company.","s":["subcontract","delegate","farm out"],"wf":[{"w":"outsourcing","p":"noun"},{"w":"outsourced","p":"adj"}],"ety":"Gabungan kata 'out' + 'source'. Muncul dalam bahasa bisnis Amerika pada tahun 1980-an ketika perusahaan mulai mengontrakkan pekerjaan ke pihak eksternal.","q":"Many companies choose to ___ their customer service to reduce costs."},
{"w":"streamline","pos":"verb","cat":"VERB","m":"to make more efficient","tr":"menyederhanakan proses","i":"to simplify a process to make it faster and more effective","e":"The new software will streamline the invoicing process.","s":["simplify","optimize","improve"],"wf":[{"w":"streamlined","p":"adj"},{"w":"streamlining","p":"noun"}],"ety":"Awalnya istilah fisika (1860-an) untuk aliran fluida yang mulus. Diterapkan pada proses bisnis di abad ke-20 untuk berarti membuat operasi lebih efisien.","q":"The new system will ___ the approval process from five steps to two."},
{"w":"reimburse","pos":"verb","cat":"VERB","m":"to pay back expenses","tr":"mengganti biaya","i":"to repay someone for money they have spent","e":"Submit your receipts and we will reimburse you within five business days.","s":["repay","refund","compensate"],"wf":[{"w":"reimbursement","p":"noun"}],"ety":"Dari bahasa Prancis 'rembourser', dari 're-' (kembali) + 'embourser' (memasukkan ke dompet). Masuk ke bahasa Inggris pada abad ke-17.","q":"Keep all your receipts and the company will ___ your travel expenses."},
{"w":"launch","pos":"verb","cat":"VERB","m":"to introduce publicly","tr":"meluncurkan","i":"to start or introduce a new product, service, or campaign","e":"The company will launch its new product line next quarter.","s":["introduce","release","unveil"],"wf":[{"w":"launch","p":"noun"},{"w":"launcher","p":"noun"}],"ety":"Dari bahasa Prancis Kuno 'lanchier' (melempar tombak). Awalnya berarti melempar; berkembang menjadi memulai sesuatu yang baru pada abad ke-17.","q":"The tech company plans to ___ its new smartphone model next month."},
{"w":"negotiate","pos":"verb","cat":"VERB","m":"to discuss to reach agreement","tr":"bernegosiasi","i":"to have formal discussions to reach a mutually acceptable outcome","e":"Both parties agreed to negotiate the terms of the contract.","s":["discuss","bargain","mediate"],"wf":[{"w":"negotiation","p":"noun"},{"w":"negotiator","p":"noun"},{"w":"negotiable","p":"adj"}],"ety":"Dari bahasa Latin 'negotiari' (menjalankan bisnis), dari 'negotium' (bisnis), dari 'nec' (tidak) + 'otium' (waktu luang). Masuk ke bahasa Inggris pada abad ke-16.","q":"The union and management will ___ a new salary agreement next week."},
{"w":"monitor","pos":"verb","cat":"VERB","m":"to watch and check","tr":"memantau","i":"to regularly observe and check the progress of something","e":"The supervisor will monitor employee performance on a monthly basis.","s":["track","oversee","observe"],"wf":[{"w":"monitoring","p":"noun"},{"w":"monitor","p":"noun"}],"ety":"Dari bahasa Latin 'monitor' (orang yang memperingatkan), dari 'monere' (memperingatkan). Makna memantau/memeriksa berkembang pada abad ke-20.","q":"The IT team will ___ the network for any unusual activity."},
{"w":"allocate","pos":"verb","cat":"VERB","m":"to assign resources","tr":"mengalokasikan","i":"to distribute resources or duties for a specific purpose","e":"The budget was allocated equally among all departments.","s":["assign","distribute","designate"],"wf":[{"w":"allocation","p":"noun"},{"w":"allocated","p":"adj"}],"ety":"Dari bahasa Latin Abad Pertengahan 'allocare' (menempatkan), dari 'ad-' (ke) + 'locare' (menempatkan). Masuk ke bahasa Inggris pada abad ke-17.","q":"The manager decided to ___ more resources to the marketing department."},
{"w":"comply","pos":"verb","cat":"VERB","m":"to follow rules","tr":"mematuhi","i":"to act in accordance with rules, regulations, or requests","e":"All staff must comply with the new workplace safety guidelines.","s":["obey","adhere to","conform to"],"wf":[{"w":"compliance","p":"noun"},{"w":"compliant","p":"adj"}],"ety":"Dari bahasa Italia 'complire' (memenuhi), dari bahasa Latin 'complere' (mengisi penuh). Masuk ke bahasa Inggris pada abad ke-17.","q":"All employees must ___ with the company's code of conduct."},
{"w":"submit","pos":"verb","cat":"VERB","m":"to hand in formally","tr":"mengajukan / menyerahkan","i":"to present a document or application for consideration","e":"Please submit your application before the deadline.","s":["hand in","present","file"],"wf":[{"w":"submission","p":"noun"},{"w":"submitted","p":"adj"}],"ety":"Dari bahasa Latin 'submittere' (menempatkan di bawah), dari 'sub-' (di bawah) + 'mittere' (mengirim). Masuk ke bahasa Inggris pada abad ke-14.","q":"Please ___ your expense report by the end of the month."},
{"w":"coordinate","pos":"verb","cat":"VERB","m":"to organize jointly","tr":"mengoordinasikan","i":"to organize people or activities so they work together effectively","e":"She was asked to coordinate the annual sales conference.","s":["organize","manage","arrange"],"wf":[{"w":"coordination","p":"noun"},{"w":"coordinator","p":"noun"}],"ety":"Dari bahasa Latin 'coordinare' (mengatur dalam urutan), dari 'co-' (bersama) + 'ordinare' (mengatur). Masuk ke bahasa Inggris pada abad ke-19.","q":"The project manager will ___ all teams to ensure the deadline is met."},
{"w":"evaluate","pos":"verb","cat":"VERB","m":"to assess carefully","tr":"mengevaluasi","i":"to judge or calculate the quality or value of something","e":"The committee will evaluate all proposals by Friday.","s":["assess","review","appraise"],"wf":[{"w":"evaluation","p":"noun"},{"w":"evaluator","p":"noun"}],"ety":"Dari bahasa Prancis 'evaluer', dari 'e-' (keluar) + 'valuer' (menilai), dari bahasa Latin 'valere' (bernilai). Masuk ke bahasa Inggris pada abad ke-19.","q":"The HR team will ___ all candidates before making a hiring decision."},
{"w":"implement","pos":"verb","cat":"VERB","m":"to put into action","tr":"menerapkan / melaksanakan","i":"to put a plan or decision into effect","e":"The new policy will be implemented starting next month.","s":["execute","apply","carry out"],"wf":[{"w":"implementation","p":"noun"},{"w":"implementer","p":"noun"}],"ety":"Dari bahasa Latin 'implementum' (pengisian), dari 'implere' (mengisi). Awalnya berarti alat atau instrumen; makna melaksanakan rencana berkembang pada abad ke-20.","q":"The company plans to ___ the new HR system across all departments."},
{"w":"verify","pos":"verb","cat":"VERB","m":"to confirm accuracy","tr":"memverifikasi","i":"to make sure that something is true or correct","e":"Please verify your contact details before submitting the form.","s":["confirm","validate","check"],"wf":[{"w":"verification","p":"noun"},{"w":"verifiable","p":"adj"}],"ety":"Dari bahasa Latin 'verificare' (membuat benar), dari 'verus' (benar) + 'facere' (membuat). Masuk ke bahasa Inggris pada abad ke-14.","q":"Please ___ that all the information on the form is correct before signing."},
{"w":"expedite","pos":"verb","cat":"VERB","m":"to speed up","tr":"mempercepat proses","i":"to make a process happen more quickly","e":"We need to expedite the shipment to meet the client deadline.","s":["accelerate","rush","fast-track"],"wf":[{"w":"expeditious","p":"adj"},{"w":"expeditiously","p":"adv"}],"ety":"Dari bahasa Latin 'expedire' (membebaskan kaki), dari 'ex-' (keluar) + 'pes/pedis' (kaki). Awalnya berarti membebaskan dari hambatan; berkembang menjadi mempercepat pada abad ke-17.","q":"Could you ___ the delivery? The client needs the goods by Friday."},
{"w":"postpone","pos":"verb","cat":"VERB","m":"to delay to a later time","tr":"menunda","i":"to arrange for something to happen at a later time than planned","e":"The board meeting has been postponed until further notice.","s":["delay","defer","reschedule"],"wf":[{"w":"postponement","p":"noun"},{"w":"postponed","p":"adj"}],"ety":"Dari bahasa Latin 'postponere' (menempatkan setelah), dari 'post-' (setelah) + 'ponere' (menempatkan). Masuk ke bahasa Inggris pada abad ke-16.","q":"Due to the storm, the company decided to ___ the outdoor event."},
{"w":"acquire","pos":"verb","cat":"VERB","m":"to obtain or buy","tr":"memperoleh / mengakuisisi","i":"to gain possession of something, especially through effort or purchase","e":"The company acquired a smaller competitor last year.","s":["obtain","purchase","gain"],"wf":[{"w":"acquisition","p":"noun"},{"w":"acquired","p":"adj"}],"ety":"Dari bahasa Latin 'acquirere' (mencari tambahan), dari 'ad-' (ke) + 'quaerere' (mencari). Masuk ke bahasa Inggris pada abad ke-15.","q":"The corporation plans to ___ three new companies this fiscal year."},
{"w":"distribute","pos":"verb","cat":"VERB","m":"to hand out or deliver","tr":"mendistribusikan","i":"to give or deliver something to a number of people","e":"The marketing team will distribute flyers at the trade show.","s":["deliver","hand out","circulate"],"wf":[{"w":"distribution","p":"noun"},{"w":"distributor","p":"noun"}],"ety":"Dari bahasa Latin 'distribuere' (membagi), dari 'dis-' (terpisah) + 'tribuere' (menugaskan). Masuk ke bahasa Inggris pada abad ke-15.","q":"The company will ___ the annual report to all shareholders next week."},
{"w":"renovate","pos":"verb","cat":"VERB","m":"to repair and improve","tr":"merenovasi","i":"to repair and improve a building or room","e":"The office will be renovated over the summer break.","s":["refurbish","restore","remodel"],"wf":[{"w":"renovation","p":"noun"},{"w":"renovated","p":"adj"}],"ety":"Dari bahasa Latin 'renovare' (memperbarui), dari 're-' (lagi) + 'novare' (membuat baru), dari 'novus' (baru). Masuk ke bahasa Inggris pada abad ke-17.","q":"The hotel plans to ___ all guest rooms before the peak season."},
{"w":"register","pos":"verb","cat":"VERB","m":"to sign up officially","tr":"mendaftar","i":"to put your name on an official list","e":"You must register for the seminar at least two weeks in advance.","s":["sign up","enroll","record"],"wf":[{"w":"registration","p":"noun"},{"w":"registered","p":"adj"},{"w":"registry","p":"noun"}],"ety":"Dari bahasa Latin Abad Pertengahan 'registrare' (mencatat), dari 'registrum' (daftar). Masuk ke bahasa Inggris pada abad ke-14.","q":"All new employees must ___ for the orientation program on their first day."},
{"w":"facilitate","pos":"verb","cat":"VERB","m":"to make easier","tr":"memudahkan / memfasilitasi","i":"to make a process or action easier or more achievable","e":"The new platform will facilitate communication between teams.","s":["enable","support","assist"],"wf":[{"w":"facilitation","p":"noun"},{"w":"facilitator","p":"noun"}],"ety":"Dari bahasa Latin 'facilis' (mudah), dari 'facere' (melakukan). Bentuk kata kerja masuk ke bahasa Inggris pada abad ke-17.","q":"The new online portal will ___ faster communication between clients and staff."},
{"w":"highlight","pos":"verb","cat":"VERB","m":"to draw attention to","tr":"menonjolkan / menyoroti","i":"to emphasize something as important","e":"The report highlights the need for better data security.","s":["emphasize","feature","showcase"],"wf":[{"w":"highlight","p":"noun"},{"w":"highlighted","p":"adj"}],"ety":"Gabungan kata 'high' + 'light'. Awalnya istilah seni lukis untuk bagian paling terang; makna kiasan menekankan sesuatu berkembang pada abad ke-20.","q":"The CEO used the presentation to ___ the company's achievements this year."},
{"w":"generate","pos":"verb","cat":"VERB","m":"to produce or create","tr":"menghasilkan","i":"to cause something to exist or occur","e":"The campaign generated significant interest from potential investors.","s":["produce","create","yield"],"wf":[{"w":"generation","p":"noun"},{"w":"generator","p":"noun"}],"ety":"Dari bahasa Latin 'generare' (melahirkan), dari 'genus' (ras, jenis). Masuk ke bahasa Inggris pada abad ke-16.","q":"The new marketing strategy is expected to ___ more leads for the sales team."},
{"w":"enhance","pos":"verb","cat":"VERB","m":"to improve quality","tr":"meningkatkan kualitas","i":"to increase or improve the quality, value, or extent of something","e":"The upgrade will enhance the performance of the entire system.","s":["improve","boost","strengthen"],"wf":[{"w":"enhancement","p":"noun"},{"w":"enhanced","p":"adj"}],"ety":"Dari bahasa Prancis Kuno 'enhaucier' (meninggikan), dari bahasa Latin 'in-' (dalam) + 'altus' (tinggi). Masuk ke bahasa Inggris pada abad ke-13.","q":"The training program will ___ employees' communication and leadership skills."},
{"w":"anticipate","pos":"verb","cat":"VERB","m":"to expect in advance","tr":"mengantisipasi / memperkirakan","i":"to expect or predict something before it happens","e":"We anticipate strong demand for the new product.","s":["expect","foresee","predict"],"wf":[{"w":"anticipation","p":"noun"},{"w":"anticipated","p":"adj"}],"ety":"Dari bahasa Latin 'anticipare' (mengambil sebelumnya), dari 'ante-' (sebelum) + 'capere' (mengambil). Masuk ke bahasa Inggris pada abad ke-16.","q":"We ___ that the new policy will reduce costs by at least 15 percent."},
{"w":"accommodate","pos":"verb","cat":"VERB","m":"to provide space or adjust","tr":"menampung / mengakomodasi","i":"to provide room for, or to adjust to meet needs","e":"The conference hall can accommodate up to 500 guests.","s":["house","hold","cater for"],"wf":[{"w":"accommodation","p":"noun"},{"w":"accommodating","p":"adj"}],"ety":"Dari bahasa Latin 'accommodare' (membuat sesuai), dari 'ad-' (ke) + 'commodus' (sesuai). Masuk ke bahasa Inggris pada abad ke-16.","q":"The new office building can ___ up to 300 employees comfortably."},
{"w":"demonstrate","pos":"verb","cat":"VERB","m":"to show clearly","tr":"mendemonstrasikan","i":"to show or prove something clearly","e":"The results demonstrate the effectiveness of the new approach.","s":["show","prove","illustrate"],"wf":[{"w":"demonstration","p":"noun"},{"w":"demonstrative","p":"adj"}],"ety":"Dari bahasa Latin 'demonstrare' (menunjukkan), dari 'de-' (sepenuhnya) + 'monstrare' (menunjukkan). Masuk ke bahasa Inggris pada abad ke-16.","q":"The sales team will ___ the new software to potential clients next week."},
{"w":"collaborate","pos":"verb","cat":"VERB","m":"to work together","tr":"berkolaborasi","i":"to work jointly with others on a project","e":"The two departments will collaborate on the new marketing campaign.","s":["cooperate","partner","team up"],"wf":[{"w":"collaboration","p":"noun"},{"w":"collaborative","p":"adj"},{"w":"collaborator","p":"noun"}],"ety":"Dari bahasa Latin 'collaborare' (bekerja bersama), dari 'col-' (bersama) + 'laborare' (bekerja). Masuk ke bahasa Inggris pada abad ke-19.","q":"The R&D and marketing teams will ___ to develop the new product launch strategy."},
{"w":"investigate","pos":"verb","cat":"VERB","m":"to examine thoroughly","tr":"menyelidiki","i":"to carry out a systematic inquiry into something","e":"The auditors were asked to investigate the financial discrepancy.","s":["examine","probe","look into"],"wf":[{"w":"investigation","p":"noun"},{"w":"investigator","p":"noun"}],"ety":"Dari bahasa Latin 'investigare' (melacak), dari 'in-' (dalam) + 'vestigare' (melacak), dari 'vestigium' (jejak kaki). Masuk ke bahasa Inggris pada abad ke-16.","q":"The compliance team was asked to ___ the reported irregularities in the accounts."},
{"w":"propose","pos":"verb","cat":"VERB","m":"to suggest formally","tr":"mengusulkan","i":"to put forward a plan or idea for consideration","e":"The manager proposed a new approach to customer service.","s":["suggest","recommend","put forward"],"wf":[{"w":"proposal","p":"noun"},{"w":"proposition","p":"noun"}],"ety":"Dari bahasa Latin 'proponere' (mengajukan), dari 'pro-' (ke depan) + 'ponere' (menempatkan). Masuk ke bahasa Inggris pada abad ke-14.","q":"The consultant will ___ a new restructuring plan at the board meeting."},
]

with open("public/games/flashcard_lengkap_intact/toeic_test06_vocab.html", "a", encoding="utf-8") as f:
    for w in words:
        f.write("  " + json.dumps(w, ensure_ascii=False) + ",\n")
print(f"Written {len(words)} verbs")
