import json, re

html = open('public/games/flashcard_lengkap_intact/toefl_test.html', encoding='utf-8').read()
script_start = html.index('<script>') + len('<script>')
state_start = html.index('// STATE')
header = html[:script_start]
engine = html[state_start:]
reading_qs = json.load(open('reading_qs.json', encoding='utf-8'))

# All 100 listening questions as clean Python dicts
L = [
 {'id':'L1','sec':'L','audio':'Test_01.mp3','grp':'Conversation 1 (Q1-5)','passage':'[Listen to a conversation between a student and a professor about a research paper deadline.]','text':'1. Why does the student visit the professor?','opts':['(A) To submit a completed paper','(B) To request an extension on her assignment','(C) To ask about the grading criteria','(D) To get feedback on her draft'],'ans':'(B) To request an extension on her assignment'},
 {'id':'L2','sec':'L','audio':'Test_01.mp3','grp':'Conversation 1 (Q1-5)','passage':'[Listen to a conversation between a student and a professor about a research paper deadline.]','text':'2. What does the professor say about the deadline?','opts':['(A) It cannot be changed under any circumstances','(B) A one-week extension is possible','(C) The deadline was already extended once','(D) Students must submit by midnight'],'ans':'(B) A one-week extension is possible'},
 {'id':'L3','sec':'L','audio':'Test_01.mp3','grp':'Conversation 1 (Q1-5)','passage':'[Listen to a conversation between a student and a professor about a research paper deadline.]','text':'3. What problem does the student mention?','opts':['(A) She lost her notes','(B) Her computer broke down','(C) She has been ill for several days','(D) She misunderstood the assignment'],'ans':'(C) She has been ill for several days'},
 {'id':'L4','sec':'L','audio':'Test_01.mp3','grp':'Conversation 1 (Q1-5)','passage':'[Listen to a conversation between a student and a professor about a research paper deadline.]','text':'4. What does the professor ask the student to provide?','opts':["(A) A doctor's note",'(B) A partial draft','(C) An email confirmation','(D) A revised outline'],'ans':"(A) A doctor's note"},
 {'id':'L5','sec':'L','audio':'Test_01.mp3','grp':'Conversation 1 (Q1-5)','passage':'[Listen to a conversation between a student and a professor about a research paper deadline.]','text':'5. What will the student most likely do next?','opts':['(A) Drop the course','(B) Submit the paper immediately','(C) Get documentation from the health center','(D) Ask another professor for help'],'ans':'(C) Get documentation from the health center'},
 {'id':'L6','sec':'L','audio':'Test_01.mp3','grp':'Lecture 1 — Astronomy (Q6-11)','passage':'[Listen to part of a lecture in an astronomy class about the formation of stars.]','text':'6. What is the lecture mainly about?','opts':['(A) The life cycle of the Sun','(B) How stars form from nebulae','(C) The discovery of new galaxies','(D) Black holes and their properties'],'ans':'(B) How stars form from nebulae'},
 {'id':'L7','sec':'L','audio':'Test_01.mp3','grp':'Lecture 1 — Astronomy (Q6-11)','passage':'[Listen to part of a lecture in an astronomy class about the formation of stars.]','text':'7. What is a nebula?','opts':['(A) A dying star','(B) A type of galaxy','(C) A cloud of gas and dust in space','(D) A planet without an atmosphere'],'ans':'(C) A cloud of gas and dust in space'},
 {'id':'L8','sec':'L','audio':'Test_01.mp3','grp':'Lecture 1 — Astronomy (Q6-11)','passage':'[Listen to part of a lecture in an astronomy class about the formation of stars.]','text':'8. According to the professor, what triggers star formation?','opts':['(A) A nearby supernova explosion','(B) Gravitational collapse of gas clouds','(C) Collision between two galaxies','(D) Solar wind from existing stars'],'ans':'(B) Gravitational collapse of gas clouds'},
 {'id':'L9','sec':'L','audio':'Test_01.mp3','grp':'Lecture 1 — Astronomy (Q6-11)','passage':'[Listen to part of a lecture in an astronomy class about the formation of stars.]','text':'9. What is a protostar?','opts':['(A) A star that has exploded','(B) An early stage of star formation before nuclear fusion begins','(C) A star with no planets','(D) A star larger than the Sun'],'ans':'(B) An early stage of star formation before nuclear fusion begins'},
 {'id':'L10','sec':'L','audio':'Test_01.mp3','grp':'Lecture 1 — Astronomy (Q6-11)','passage':'[Listen to part of a lecture in an astronomy class about the formation of stars.]','text':'10. What determines the final size of a star?','opts':['(A) The temperature of the nebula','(B) The distance from the galactic center','(C) The amount of mass in the original gas cloud','(D) The speed of rotation'],'ans':'(C) The amount of mass in the original gas cloud'},
 {'id':'L11','sec':'L','audio':'Test_01.mp3','grp':'Lecture 1 — Astronomy (Q6-11)','passage':'[Listen to part of a lecture in an astronomy class about the formation of stars.]','text':'11. What does the professor say about the Sun?','opts':['(A) It is unusually large for its type','(B) It is a medium-sized star that formed from a nebula','(C) It will become a black hole','(D) It formed 10 billion years ago'],'ans':'(B) It is a medium-sized star that formed from a nebula'},
 {'id':'L12','sec':'L','audio':'Test_01.mp3','grp':'Conversation 2 (Q12-16)','passage':'[Listen to a conversation between two students planning a group presentation.]','text':'12. What are the students discussing?','opts':['(A) A lab experiment','(B) A group presentation assignment','(C) A study schedule for finals','(D) A campus event they are organizing'],'ans':'(B) A group presentation assignment'},
 {'id':'L13','sec':'L','audio':'Test_01.mp3','grp':'Conversation 2 (Q12-16)','passage':'[Listen to a conversation between two students planning a group presentation.]','text':'13. What topic did they choose for the presentation?','opts':['(A) Climate change','(B) Artificial intelligence in healthcare','(C) The history of the internet','(D) Renewable energy sources'],'ans':'(B) Artificial intelligence in healthcare'},
 {'id':'L14','sec':'L','audio':'Test_01.mp3','grp':'Conversation 2 (Q12-16)','passage':'[Listen to a conversation between two students planning a group presentation.]','text':'14. What does the man volunteer to do?','opts':['(A) Design the slides','(B) Conduct the research','(C) Present the introduction','(D) Find a meeting room'],'ans':'(A) Design the slides'},
 {'id':'L15','sec':'L','audio':'Test_01.mp3','grp':'Conversation 2 (Q12-16)','passage':'[Listen to a conversation between two students planning a group presentation.]','text':'15. When do they plan to meet next?','opts':["(A) Tomorrow morning",'(B) This weekend',"(C) After Thursday's class",'(D) Next Monday'],'ans':"(C) After Thursday's class"},
 {'id':'L16','sec':'L','audio':'Test_01.mp3','grp':'Conversation 2 (Q12-16)','passage':'[Listen to a conversation between two students planning a group presentation.]','text':'16. What concern does the woman express?','opts':['(A) The topic is too broad','(B) They do not have enough time','(C) One group member is unreliable','(D) The professor dislikes their topic'],'ans':'(A) The topic is too broad'},
 {'id':'L17','sec':'L','audio':'Test_01.mp3','grp':'Lecture 2 — Economics (Q17-22)','passage':'[Listen to part of a lecture in an economics class about supply and demand.]','text':'17. What economic concept is the lecture about?','opts':['(A) Inflation and deflation','(B) The law of supply and demand','(C) International trade agreements','(D) Government fiscal policy'],'ans':'(B) The law of supply and demand'},
 {'id':'L18','sec':'L','audio':'Test_01.mp3','grp':'Lecture 2 — Economics (Q17-22)','passage':'[Listen to part of a lecture in an economics class about supply and demand.]','text':'18. According to the professor, what happens when demand increases but supply stays the same?','opts':['(A) Prices fall','(B) Prices rise','(C) Supply automatically increases','(D) The market collapses'],'ans':'(B) Prices rise'},
 {'id':'L19','sec':'L','audio':'Test_01.mp3','grp':'Lecture 2 — Economics (Q17-22)','passage':'[Listen to part of a lecture in an economics class about supply and demand.]','text':'19. What example does the professor use to illustrate the concept?','opts':['(A) The housing market','(B) The price of gasoline','(C) The stock market','(D) Agricultural commodity prices'],'ans':'(A) The housing market'},
 {'id':'L20','sec':'L','audio':'Test_01.mp3','grp':'Lecture 2 — Economics (Q17-22)','passage':'[Listen to part of a lecture in an economics class about supply and demand.]','text':'20. What is the equilibrium price?','opts':['(A) The lowest price a seller will accept','(B) The price set by the government','(C) The price at which supply equals demand','(D) The average price across all markets'],'ans':'(C) The price at which supply equals demand'},
 {'id':'L21','sec':'L','audio':'Test_01.mp3','grp':'Lecture 2 — Economics (Q17-22)','passage':'[Listen to part of a lecture in an economics class about supply and demand.]','text':'21. What does the professor say about price ceilings?','opts':['(A) They always benefit consumers','(B) They can lead to shortages','(C) They are rarely used in modern economies','(D) They increase supply'],'ans':'(B) They can lead to shortages'},
 {'id':'L22','sec':'L','audio':'Test_01.mp3','grp':'Lecture 2 — Economics (Q17-22)','passage':'[Listen to part of a lecture in an economics class about supply and demand.]','text':'22. What assignment does the professor give for next class?','opts':['(A) Read chapter 4','(B) Write a one-page analysis of a market','(C) Find a news article about price changes','(D) Complete a problem set'],'ans':'(C) Find a news article about price changes'},
 {'id':'L23','sec':'L','audio':'Test_01.mp3','grp':'Lecture 3 — Literature (Q23-28)','passage':'[Listen to part of a lecture in a literature class about symbolism in novels.]','text':'23. What literary device is the focus of the lecture?','opts':['(A) Metaphor','(B) Foreshadowing','(C) Symbolism','(D) Irony'],'ans':'(C) Symbolism'},
 {'id':'L24','sec':'L','audio':'Test_01.mp3','grp':'Lecture 3 — Literature (Q23-28)','passage':'[Listen to part of a lecture in a literature class about symbolism in novels.]','text':'24. Which novel does the professor use as the main example?','opts':['(A) The Great Gatsby','(B) To Kill a Mockingbird','(C) 1984','(D) The Catcher in the Rye'],'ans':'(A) The Great Gatsby'},
 {'id':'L25','sec':'L','audio':'Test_01.mp3','grp':'Lecture 3 — Literature (Q23-28)','passage':'[Listen to part of a lecture in a literature class about symbolism in novels.]','text':'25. What does the green light in the novel symbolize?','opts':['(A) Jealousy and envy','(B) Hope and the American Dream','(C) Wealth and materialism','(D) Death and decay'],'ans':'(B) Hope and the American Dream'},
 {'id':'L26','sec':'L','audio':'Test_01.mp3','grp':'Lecture 3 — Literature (Q23-28)','passage':'[Listen to part of a lecture in a literature class about symbolism in novels.]','text':'26. According to the professor, why is symbolism important in literature?','opts':['(A) It makes stories longer','(B) It allows authors to convey complex ideas indirectly','(C) It replaces the need for character development','(D) It is required by literary conventions'],'ans':'(B) It allows authors to convey complex ideas indirectly'},
 {'id':'L27','sec':'L','audio':'Test_01.mp3','grp':'Lecture 3 — Literature (Q23-28)','passage':'[Listen to part of a lecture in a literature class about symbolism in novels.]','text':'27. What does the professor say about the Valley of Ashes?','opts':['(A) It represents the beauty of industrial progress','(B) It symbolizes the moral decay beneath the glamour of wealth','(C) It is where the main character lives','(D) It has no symbolic meaning'],'ans':'(B) It symbolizes the moral decay beneath the glamour of wealth'},
 {'id':'L28','sec':'L','audio':'Test_01.mp3','grp':'Lecture 3 — Literature (Q23-28)','passage':'[Listen to part of a lecture in a literature class about symbolism in novels.]','text':'28. What does the professor ask students to do for homework?','opts':['(A) Write an essay about symbolism','(B) Read the next two chapters','(C) Identify three symbols in a novel of their choice','(D) Watch a film adaptation'],'ans':'(C) Identify three symbols in a novel of their choice'},
 {'id':'L29','sec':'L','audio':'Test_01.mp3','grp':'Conversation 3 (Q29-33)','passage':'[Listen to a conversation between a student and a university advisor about course registration.]','text':'29. Why does the student visit the advisor?','opts':['(A) To change her major','(B) To get help registering for next semester courses','(C) To appeal a grade','(D) To apply for a scholarship'],'ans':'(B) To get help registering for next semester courses'},
 {'id':'L30','sec':'L','audio':'Test_01.mp3','grp':'Conversation 3 (Q29-33)','passage':'[Listen to a conversation between a student and a university advisor about course registration.]','text':'30. What problem does the student have with her schedule?','opts':['(A) Two required courses are at the same time','(B) She does not meet the prerequisites','(C) The courses she wants are full','(D) She has too many credits'],'ans':'(A) Two required courses are at the same time'},
 {'id':'L31','sec':'L','audio':'Test_01.mp3','grp':'Conversation 3 (Q29-33)','passage':'[Listen to a conversation between a student and a university advisor about course registration.]','text':'31. What solution does the advisor suggest?','opts':['(A) Take one course online','(B) Wait until next year','(C) Speak to the department chair','(D) Drop one course and take it in summer'],'ans':'(D) Drop one course and take it in summer'},
 {'id':'L32','sec':'L','audio':'Test_01.mp3','grp':'Conversation 3 (Q29-33)','passage':'[Listen to a conversation between a student and a university advisor about course registration.]','text':'32. What does the advisor say about the summer course?','opts':['(A) It is more expensive','(B) It covers the same material as the regular course','(C) It is only available online','(D) It has limited enrollment'],'ans':'(B) It covers the same material as the regular course'},
 {'id':'L33','sec':'L','audio':'Test_01.mp3','grp':'Conversation 3 (Q29-33)','passage':'[Listen to a conversation between a student and a university advisor about course registration.]','text':'33. What will the student do after the meeting?','opts':['(A) Register for the summer course immediately','(B) Think about the options and return tomorrow','(C) Email the professor directly','(D) Check the online course catalog'],'ans':'(B) Think about the options and return tomorrow'},
]
print(f'L1-33: {len(L)}')
L += [
 {'id':'L34','sec':'L','audio':'Test_01.mp3','grp':'Lecture 4 — Environmental Science (Q34-39)','passage':'[Listen to part of a lecture in an environmental science class about deforestation.]','text':'34. What is the main topic of the lecture?','opts':['(A) The benefits of reforestation','(B) Causes and effects of deforestation','(C) Wildlife conservation programs','(D) Climate change and ocean levels'],'ans':'(B) Causes and effects of deforestation'},
]
print(len(L))
