// ═══════════════════════════════════════════
// PART 5 — Q101–130
// ═══════════════════════════════════════════
const part5 = [
  { id:101, part:5, text:'Former Sendai Company CEO Ken Nakata spoke about _______ career experiences.', options:['(A) he','(B) his','(C) him','(D) himself'], answer:'(B) his' },
  { id:102, part:5, text:'Passengers who will be taking a _______ domestic flight should go to Terminal A.', options:['(A) connectivity','(B) connects','(C) connect','(D) connecting'], answer:'(D) connecting' },
  { id:103, part:5, text:'Fresh and _______ apple-cider donuts are available at Oakcrest Orchard\'s retail shop for $6 per dozen.', options:['(A) eaten','(B) open','(C) tasty','(D) free'], answer:'(C) tasty' },
  { id:104, part:5, text:'Zahn Flooring has the widest selection of _______ in the United Kingdom.', options:['(A) paints','(B) tiles','(C) furniture','(D) curtains'], answer:'(B) tiles' },
  { id:105, part:5, text:'One responsibility of the IT department is to ensure that the company is using _______ software.', options:['(A) update','(B) updating','(C) updates','(D) updated'], answer:'(D) updated' },
  { id:106, part:5, text:'It is wise to check a company\'s dress code _______ visiting its head office.', options:['(A) so','(B) how','(C) like','(D) before'], answer:'(D) before' },
  { id:107, part:5, text:'Wexler Store\'s management team expects that employees will _______ support any new hires.', options:['(A) enthusiastically','(B) enthusiasm','(C) enthusiastic','(D) enthused'], answer:'(A) enthusiastically' },
  { id:108, part:5, text:'Wheel alignments and brake system _______ are part of our vehicle service plan.', options:['(A) inspects','(B) inspector','(C) inspected','(D) inspections'], answer:'(D) inspections' },
  { id:109, part:5, text:'Registration for the Marketing Coalition Conference is now open _______ September 30.', options:['(A) until','(B) into','(C) yet','(D) while'], answer:'(A) until' },
  { id:110, part:5, text:'Growth in the home entertainment industry has been _______ this quarter.', options:['(A) separate','(B) limited','(C) willing','(D) assorted'], answer:'(B) limited' },
  { id:111, part:5, text:'Hawson Furniture will be making _______ on the east side of town on Thursday.', options:['(A) deliveries','(B) delivered','(C) deliver','(D) deliverable'], answer:'(A) deliveries' },
  { id:112, part:5, text:'The Marlton City Council does not have the authority to _______ parking on city streets.', options:['(A) drive','(B) prohibit','(C) bother','(D) travel'], answer:'(B) prohibit' },
  { id:113, part:5, text:'Project Earth Group is _______ for ways to reduce transport-related greenhouse gas emissions.', options:['(A) looking','(B) seeing','(C) driving','(D) leaning'], answer:'(A) looking' },
  { id:114, part:5, text:'Our skilled tailors are happy to design a custom-made suit that fits your style and budget _______.', options:['(A) perfect','(B) perfects','(C) perfectly','(D) perfection'], answer:'(C) perfectly' },
  { id:115, part:5, text:'Project manager Hannah Chung has proved to be very _______ with completing company projects.', options:['(A) helpfulness','(B) help','(C) helpfully','(D) helpful'], answer:'(D) helpful' },
  { id:116, part:5, text:'Lehua Vacation Club members will receive double points _______ the month of August at participating hotels.', options:['(A) onto','(B) above','(C) during','(D) between'], answer:'(C) during' },
  { id:117, part:5, text:'The costumes were not received _______ enough to be used in the first dress rehearsal.', options:['(A) far','(B) very','(C) almost','(D) soon'], answer:'(D) soon' },
  { id:118, part:5, text:'As a former publicist for several renowned orchestras, Mr. Wu would excel in the role of event _______.', options:['(A) organized','(B) organizer','(C) organizes','(D) organizational'], answer:'(B) organizer' },
  { id:119, part:5, text:'The northbound lane on Davis Street will be _______ closed because of the city\'s bridge reinforcement project.', options:['(A) temporarily','(B) competitively','(C) recently','(D) collectively'], answer:'(A) temporarily' },
  { id:120, part:5, text:'Airline representatives must handle a wide range of passenger issues, _______ missed connections to lost luggage.', options:['(A) from','(B) under','(C) on','(D) against'], answer:'(A) from' },
  { id:121, part:5, text:'The meeting notes were _______ deleted, but Mr. Hahm was able to recreate them from memory.', options:['(A) accident','(B) accidental','(C) accidents','(D) accidentally'], answer:'(D) accidentally' },
  { id:122, part:5, text:'The current issue of Farming Scene magazine predicts that the price of corn will rise 5 percent over the _______ year.', options:['(A) next','(B) with','(C) which','(D) now'], answer:'(A) next' },
  { id:123, part:5, text:'Anyone who still _______ to take the fire safety training should do so before the end of the month.', options:['(A) needing','(B) needs','(C) has needed','(D) were needing'], answer:'(B) needs' },
  { id:124, part:5, text:'Emerging technologies have _______ begun to transform the shipping industry in ways that were once unimaginable.', options:['(A) already','(B) exactly','(C) hardly','(D) closely'], answer:'(A) already' },
  { id:125, part:5, text:'The company handbook outlines the high _______ that employees are expected to meet every day.', options:['(A) experts','(B) accounts','(C) recommendations','(D) standards'], answer:'(D) standards' },
  { id:126, part:5, text:'Because _______ of the board members have scheduling conflicts, the board meeting will be moved to a date when all can attend.', options:['(A) any','(B) everybody','(C) those','(D) some'], answer:'(D) some' },
  { id:127, part:5, text:'The project _______ the collaboration of several teams across the company.', options:['(A) passed','(B) decided','(C) required','(D) performed'], answer:'(C) required' },
  { id:128, part:5, text:'We cannot send the store\'s coupon booklet to the printers until it _______ by Ms. Jeon.', options:['(A) is approving','(B) approves','(C) has been approved','(D) will be approved'], answer:'(C) has been approved' },
  { id:129, part:5, text:'_______ the closure of Verdigold Transport Services, we are looking for a new shipping company.', options:['(A) In spite of','(B) Just as','(C) In light of','(D) According to'], answer:'(C) In light of' },
  { id:130, part:5, text:'The _______ information provided by Uniss Bank\'s brochure helps applicants understand the terms of their loans.', options:['(A) arbitrary','(B) supplemental','(C) superfluous','(D) potential'], answer:'(B) supplemental' },
]

// ═══════════════════════════════════════════
// PART 6 — Q131–146
// ═══════════════════════════════════════════
const part6 = [
  // Passage 1: Q131–134
  { id:131, part:6, passageId:'p6-1', groupTitle:'Questions 131–134 refer to the following announcement.',
    passageText:`Come to the Maxley Heights Center for Horticulture and learn how to create a beautiful, eco-friendly garden for your home or business. [131] We will teach you how to plant a rain garden, which is simply a shallow sunken garden [132] a special soil mix to filter pollutants from rainwater flowing from nearby roads and rooftops. These gardens can be landscaped with native plants and flowers. [133] rain gardens are always beneficial to the local environment. Among other things, [134] improve drainage and protect rivers and streams.\n\nTo register, visit www.maxley-horticulture.org.`,
    text:'131. Select the best answer for blank [131].',
    options:['(A) Children of all ages will enjoy the new exhibits.','(B) Learn about rainfall patterns across the region.','(C) Build a set of simple patio furniture with easy-to-acquire materials.','(D) Next Saturday at 4 P.M., we are hosting a free workshop for the public.'],
    answer:'(D) Next Saturday at 4 P.M., we are hosting a free workshop for the public.' },
  { id:132, part:6, passageId:'p6-1', groupTitle:'Questions 131–134 refer to the following announcement.',
    passageText:`Come to the Maxley Heights Center for Horticulture and learn how to create a beautiful, eco-friendly garden for your home or business. [131] We will teach you how to plant a rain garden, which is simply a shallow sunken garden [132] a special soil mix to filter pollutants from rainwater flowing from nearby roads and rooftops. These gardens can be landscaped with native plants and flowers. [133] rain gardens are always beneficial to the local environment. Among other things, [134] improve drainage and protect rivers and streams.\n\nTo register, visit www.maxley-horticulture.org.`,
    text:'132. Select the best answer for blank [132].',
    options:['(A) to use','(B) used to','(C) by using','(D) that uses'],
    answer:'(D) that uses' },
  { id:133, part:6, passageId:'p6-1', groupTitle:'Questions 131–134 refer to the following announcement.',
    passageText:`Come to the Maxley Heights Center for Horticulture and learn how to create a beautiful, eco-friendly garden for your home or business. [131] We will teach you how to plant a rain garden, which is simply a shallow sunken garden [132] a special soil mix to filter pollutants from rainwater flowing from nearby roads and rooftops. These gardens can be landscaped with native plants and flowers. [133] rain gardens are always beneficial to the local environment. Among other things, [134] improve drainage and protect rivers and streams.\n\nTo register, visit www.maxley-horticulture.org.`,
    text:'133. Select the best answer for blank [133].',
    options:['(A) Best of all','(B) For example','(C) In any event','(D) As a matter of fact'],
    answer:'(A) Best of all' },
  { id:134, part:6, passageId:'p6-1', groupTitle:'Questions 131–134 refer to the following announcement.',
    passageText:`Come to the Maxley Heights Center for Horticulture and learn how to create a beautiful, eco-friendly garden for your home or business. [131] We will teach you how to plant a rain garden, which is simply a shallow sunken garden [132] a special soil mix to filter pollutants from rainwater flowing from nearby roads and rooftops. These gardens can be landscaped with native plants and flowers. [133] rain gardens are always beneficial to the local environment. Among other things, [134] improve drainage and protect rivers and streams.\n\nTo register, visit www.maxley-horticulture.org.`,
    text:'134. Select the best answer for blank [134].',
    options:['(A) we','(B) they','(C) both','(D) yours'],
    answer:'(B) they' },

  // Passage 2: Q135–138
  { id:135, part:6, passageId:'p6-2', groupTitle:'Questions 135–138 refer to the following letter.',
    passageText:`31 July\n\nDear Mr. Dombo,\n\nThank you for your [135] support in helping me to plan the opening gala for Tokyo's fashion week. The event was a huge success, and I was honored to work with you. I know that our attendees follow your work closely, and they loved the designs you contributed for this event.\n\nYour designs received a lot of [136] on social media. Shows like this will keep Tokyo on the map as a premier fashion centre. [137] I realize that the multiple delays made the planning no easy task. The auction [138] our Young Designers Award program is coming up soon and I look forward to working with you on that as well.\n\nSincerely,\nAsahi Ishioka\nDirector, Japanese Guild of Fashion Designers`,
    text:'135. Select the best answer for blank [135].',
    options:['(A) amazed','(B) amazement','(C) amazing','(D) amazingly'],
    answer:'(C) amazing' },
  { id:136, part:6, passageId:'p6-2', groupTitle:'Questions 135–138 refer to the following letter.',
    passageText:`31 July\n\nDear Mr. Dombo,\n\nThank you for your [135] support in helping me to plan the opening gala for Tokyo's fashion week. The event was a huge success, and I was honored to work with you. I know that our attendees follow your work closely, and they loved the designs you contributed for this event.\n\nYour designs received a lot of [136] on social media. Shows like this will keep Tokyo on the map as a premier fashion centre. [137] I realize that the multiple delays made the planning no easy task. The auction [138] our Young Designers Award program is coming up soon and I look forward to working with you on that as well.\n\nSincerely,\nAsahi Ishioka\nDirector, Japanese Guild of Fashion Designers`,
    text:'136. Select the best answer for blank [136].',
    options:['(A) attention','(B) proposals','(C) innovation','(D) criticism'],
    answer:'(A) attention' },
  { id:137, part:6, passageId:'p6-2', groupTitle:'Questions 135–138 refer to the following letter.',
    passageText:`31 July\n\nDear Mr. Dombo,\n\nThank you for your [135] support in helping me to plan the opening gala for Tokyo's fashion week. The event was a huge success, and I was honored to work with you. I know that our attendees follow your work closely, and they loved the designs you contributed for this event.\n\nYour designs received a lot of [136] on social media. Shows like this will keep Tokyo on the map as a premier fashion centre. [137] I realize that the multiple delays made the planning no easy task. The auction [138] our Young Designers Award program is coming up soon and I look forward to working with you on that as well.\n\nSincerely,\nAsahi Ishioka\nDirector, Japanese Guild of Fashion Designers`,
    text:'137. Select the best answer for blank [137].',
    options:['(A) Several other events have gone surprisingly well.','(B) Thank you also for your flexibility in planning the event.','(C) Please stop by our office the next time you are in the city.','(D) Tokyo is a top tourism destination for many reasons.'],
    answer:'(B) Thank you also for your flexibility in planning the event.' },
  { id:138, part:6, passageId:'p6-2', groupTitle:'Questions 135–138 refer to the following letter.',
    passageText:`31 July\n\nDear Mr. Dombo,\n\nThank you for your [135] support in helping me to plan the opening gala for Tokyo's fashion week. The event was a huge success, and I was honored to work with you. I know that our attendees follow your work closely, and they loved the designs you contributed for this event.\n\nYour designs received a lot of [136] on social media. Shows like this will keep Tokyo on the map as a premier fashion centre. [137] I realize that the multiple delays made the planning no easy task. The auction [138] our Young Designers Award program is coming up soon and I look forward to working with you on that as well.\n\nSincerely,\nAsahi Ishioka\nDirector, Japanese Guild of Fashion Designers`,
    text:'138. Select the best answer for blank [138].',
    options:['(A) will benefit','(B) to benefit','(C) has benefited','(D) benefits'],
    answer:'(D) benefits' },

  // Passage 3: Q139–142
  { id:139, part:6, passageId:'p6-3', groupTitle:'Questions 139–142 refer to the following e-mail.',
    passageText:`From: Patron Services <patronservices@menachinlibrary.org>\nTo: Edgar Hughes <hughese98@villachesta.com>\nSubject: Card expiration date approaching\nDate: December 3\n\nDear Mr. Hughes,\n\nPlease be advised that your Mena Chin Library card will expire one month from today. [139] must be renewed if you intend to keep your membership for the coming year. This can be done at the information desk at any branch location. [140]\n\n[141] you decide to close your account, no action is necessary. Failure to complete your renewal by the [142] date will result in the expiration of your library privileges.\n\nIf you have any questions about this notice, or about general library services, you may reply directly to this e-mail.\n\nSincerely,\nPatron Services`,
    text:'139. Select the best answer for blank [139].',
    options:['(A) It','(B) You','(C) Our','(D) Each'],
    answer:'(A) It' },
  { id:140, part:6, passageId:'p6-3', groupTitle:'Questions 139–142 refer to the following e-mail.',
    passageText:`From: Patron Services <patronservices@menachinlibrary.org>\nTo: Edgar Hughes <hughese98@villachesta.com>\nSubject: Card expiration date approaching\nDate: December 3\n\nDear Mr. Hughes,\n\nPlease be advised that your Mena Chin Library card will expire one month from today. [139] must be renewed if you intend to keep your membership for the coming year. This can be done at the information desk at any branch location. [140]\n\n[141] you decide to close your account, no action is necessary. Failure to complete your renewal by the [142] date will result in the expiration of your library privileges.\n\nIf you have any questions about this notice, or about general library services, you may reply directly to this e-mail.\n\nSincerely,\nPatron Services`,
    text:'140. Select the best answer for blank [140].',
    options:['(A) To sign up for a card, visit your local library branch.','(B) For questions about library membership, please visit our Web site.','(C) Renewal must be completed at least one week before your card expires.','(D) You may opt out of this program at any time.'],
    answer:'(C) Renewal must be completed at least one week before your card expires.' },
  { id:141, part:6, passageId:'p6-3', groupTitle:'Questions 139–142 refer to the following e-mail.',
    passageText:`From: Patron Services <patronservices@menachinlibrary.org>\nTo: Edgar Hughes <hughese98@villachesta.com>\nSubject: Card expiration date approaching\nDate: December 3\n\nDear Mr. Hughes,\n\nPlease be advised that your Mena Chin Library card will expire one month from today. [139] must be renewed if you intend to keep your membership for the coming year. This can be done at the information desk at any branch location. [140]\n\n[141] you decide to close your account, no action is necessary. Failure to complete your renewal by the [142] date will result in the expiration of your library privileges.\n\nIf you have any questions about this notice, or about general library services, you may reply directly to this e-mail.\n\nSincerely,\nPatron Services`,
    text:'141. Select the best answer for blank [141].',
    options:['(A) Also','(B) Should','(C) Because','(D) Although'],
    answer:'(B) Should' },
  { id:142, part:6, passageId:'p6-3', groupTitle:'Questions 139–142 refer to the following e-mail.',
    passageText:`From: Patron Services <patronservices@menachinlibrary.org>\nTo: Edgar Hughes <hughese98@villachesta.com>\nSubject: Card expiration date approaching\nDate: December 3\n\nDear Mr. Hughes,\n\nPlease be advised that your Mena Chin Library card will expire one month from today. [139] must be renewed if you intend to keep your membership for the coming year. This can be done at the information desk at any branch location. [140]\n\n[141] you decide to close your account, no action is necessary. Failure to complete your renewal by the [142] date will result in the expiration of your library privileges.\n\nIf you have any questions about this notice, or about general library services, you may reply directly to this e-mail.\n\nSincerely,\nPatron Services`,
    text:'142. Select the best answer for blank [142].',
    options:['(A) specifically','(B) specifics','(C) specified','(D) specificity'],
    answer:'(C) specified' },

  // Passage 4: Q143–146
  { id:143, part:6, passageId:'p6-4', groupTitle:'Questions 143–146 refer to the following letter.',
    passageText:`April 7\n\nDear Ms. Burwell,\n\nI am Omar Ridha, the manager of Droplight Studio. [143] We offer a full range of photography services for real estate professionals like you. We take pride in composing interior and exterior shots that make a property look its best. Droplight Studio spares no effort in [144] superior digital images. [145] our professional-grade equipment, lighting, and staging techniques allow us to highlight the best features of a property. And once the photo shoot is over, every image receives [146] expert editing. All these services come standard in every package.\n\nPlease visit our Web site to view our work as well as our pricing and scheduling information.\n\nSincerely,\nOmar Ridha, Droplight Studio`,
    text:'143. Select the best answer for blank [143].',
    options:['(A) I would like to introduce you to our business.','(B) Great photographs can make your property stand out.','(C) We are looking forward to your visit.','(D) It was the first studio of its kind to open in this area.'],
    answer:'(A) I would like to introduce you to our business.' },
  { id:144, part:6, passageId:'p6-4', groupTitle:'Questions 143–146 refer to the following letter.',
    passageText:`April 7\n\nDear Ms. Burwell,\n\nI am Omar Ridha, the manager of Droplight Studio. [143] We offer a full range of photography services for real estate professionals like you. We take pride in composing interior and exterior shots that make a property look its best. Droplight Studio spares no effort in [144] superior digital images. [145] our professional-grade equipment, lighting, and staging techniques allow us to highlight the best features of a property. And once the photo shoot is over, every image receives [146] expert editing. All these services come standard in every package.\n\nPlease visit our Web site to view our work as well as our pricing and scheduling information.\n\nSincerely,\nOmar Ridha, Droplight Studio`,
    text:'144. Select the best answer for blank [144].',
    options:['(A) researching','(B) creating','(C) purchasing','(D) displaying'],
    answer:'(B) creating' },
  { id:145, part:6, passageId:'p6-4', groupTitle:'Questions 143–146 refer to the following letter.',
    passageText:`April 7\n\nDear Ms. Burwell,\n\nI am Omar Ridha, the manager of Droplight Studio. [143] We offer a full range of photography services for real estate professionals like you. We take pride in composing interior and exterior shots that make a property look its best. Droplight Studio spares no effort in [144] superior digital images. [145] our professional-grade equipment, lighting, and staging techniques allow us to highlight the best features of a property. And once the photo shoot is over, every image receives [146] expert editing. All these services come standard in every package.\n\nPlease visit our Web site to view our work as well as our pricing and scheduling information.\n\nSincerely,\nOmar Ridha, Droplight Studio`,
    text:'145. Select the best answer for blank [145].',
    options:['(A) If not','(B) By comparison','(C) Otherwise','(D) Indeed'],
    answer:'(D) Indeed' },
  { id:146, part:6, passageId:'p6-4', groupTitle:'Questions 143–146 refer to the following letter.',
    passageText:`April 7\n\nDear Ms. Burwell,\n\nI am Omar Ridha, the manager of Droplight Studio. [143] We offer a full range of photography services for real estate professionals like you. We take pride in composing interior and exterior shots that make a property look its best. Droplight Studio spares no effort in [144] superior digital images. [145] our professional-grade equipment, lighting, and staging techniques allow us to highlight the best features of a property. And once the photo shoot is over, every image receives [146] expert editing. All these services come standard in every package.\n\nPlease visit our Web site to view our work as well as our pricing and scheduling information.\n\nSincerely,\nOmar Ridha, Droplight Studio`,
    text:'146. Select the best answer for blank [146].',
    options:['(A) receives','(B) is receiving','(C) had received','(D) had to receive'],
    answer:'(A) receives' },
]
